language: java

jdk:
  - oraclejdk8

cache:
  directories:
    - $HOME/.m2

sudo: false

install: true

script:
  - ./mvnw clean verify -Pneo4j-3.5

after_success:
  - bash <(curl -s https://codecov.io/bash)
