= Changes

== 3.3.5

* [bug] Proper conjunct (nested) filters on relationship queries.
* [dependencies] Bump io.github.classgraph:classgraph to 4.8.179.
* [bug] Be lenient with ambiguity when checking for resolved classes.

== 3.3.4

* [dependencies] Bump default driver version to latest 4.4.x series.
* [dependencies] Bump io.github.classgraph:classgraph (#1073)

== 3.3.3

* Fix class loading problem in async environments.

== 3.3.2

* Make session related config of the BoltDriver available without complete driver reconfiguration.

== 3.3.1

* [feature] Add "app" metadata to newly created native Bolt transactions.
* [bug] Fix tests for GH-957.
* [feature] Add dynamic properties support for collections.
* [improvement] Don't rely on db ids for testing.

== 3.3.0

First release in the 3.3.x line. No changes compared to the latest 3.2.42 release, but using the latest Neo4j Java 4.4 driver as a baseline dependencies. If you don't manage the driver in your application yourself, this will affect your dependencies as well. By upgrading from a 4.0 driver to the 4.4 driver as baseline, Neo4j-OGM 3.3 effectively drops support for all versions of Neo4j database prior to 3.5.

Future supported versions of Neo4j-OGM will be 3.3 and 4.x. Neo4j-OGM 3.3 is for all projects that still require support for Neo4j 4.4 and 3.5. Neo4j-OGM 4.x is for all projects on Neo4j 4.4 or 5.
