[[tutorial:configuration]]
= Configuring Neo4j-OGM

Neo4j-OGM depends on the Neo4j Java driver for interactions with the database.
The driver itself uses the Bolt protocol to communicate with the Neo4j instance.

[[tutorial:configuration:dependencies]]
== Dependencies

To start with Neo4j-OGM we need to add the core and Bolt dependency to our project.
Even though Neo4j-OGM 4+ only provides support for connections via Bolt,
the explicit dependency definition is needed.

.Maven dependency for Neo4j-OGM
[source,xml,subs="attributes+"]
----
<dependencies>
    <dependency>
        <groupId>org.neo4j</groupId>
        <artifactId>neo4j-ogm-core</artifactId>
        <version>{ogm-version}</version>
    </dependency>
    <dependency>
        <groupId>org.neo4j</groupId>
        <artifactId>neo4j-ogm-bolt-driver</artifactId>
        <version>{ogm-version}</version>
    </dependency>
</dependencies>
----
If you are using Gradle or other systems, please do so accordingly.

Refer to <<reference:getting-started:dependency-management, Dependency Management>> for more information on dependencies.

[[tutorial:configuration:sessionfactory]]
== Neo4j-OGM configuration

The configuration of Neo4j-OGM has two parts.
First the definition of the `SessionFactory` configuration is needed.
This is where you define the database connection.
The most common parameters here are the Neo4j uri and the credentials, you want Neo4j-OGM to use for the connection.

The second step is the application specific definition of the package(s), Neo4j-OGM should scan for eligible domain classes.

[source, java]
----
Configuration configuration = new Configuration.Builder()
    .uri("neo4j://localhost:7687")
    .credentials("neo4j", "verysecret")
    .build();

SessionFactory sessionFactory = new SessionFactory(configuration, "org.neo4j.ogm.example");
----
