[[tutorial:configuration]]
= Configuring the OGM

Neo4j OGM 2.x supports several drivers:

* Bolt - the lightning fast native driver for Neo4j.
* HTTP - the original transactional HTTP endpoint for remote Neo4j deployments.
* Embedded - for embedded deployments within a Java application.

Our sample application will use the Bolt driver.

[[tutorial:configuration:gradle]]
== Setting up with Gradle

The demo application uses https://gradle.org/[Gradle] as a build system.

Before we can use the library, we need to add a dependency.

.Gradle dependencies for Neo4j OGM 2.x
[source,groovy]
----
compile "org.neo4j:neo4j-ogm-core:{version}"
runtime "org.neo4j:neo4j-ogm-bolt-driver:{version}"
----

Refer to <<reference-setup>> for more information on dependencies.

[[tutorial:configuration:driver]]
== Specifying the driver to the OGM

Since the OGM works against both remote and embedded servers, we'll need to configure it to use the appropriate driver.
We do this by providing a file called `ogm.properties` at the root of the classpath. In our application this can be
found at: `src/main/resources/`.

[source, properties]
----
driver=org.neo4j.ogm.drivers.bolt.driver.BoltDriver
URI=bolt://localhost
# Set the username and password to your Neo4j 3.0+ database.
username=
password=
----

We have now set up the Bolt Driver to connect to our local Neo4j server.


