[[introduction]]
= Introduction

[abstract]
--
This chapter is an introduction to graph databases, Neo4j, and the Neo4j object-graph mapping library (Neo4j-OGM).
It also outlines requirements and where to get support.

If you are already familiar with Neo4j and Neo4j-OGM, feel free to jump directly
to the <<tutorial, tutorial>> or <<reference, reference>> sections.
--

[[introduction:ogm]]
== What is an OGM?

An OGM (Object Graph Mapper) maps nodes and relationships in the graph to objects and references in a domain model.
Object instances are mapped to nodes while object references are mapped using relationships, or serialized to properties.
JVM primitives are mapped to node or relationship properties.
An OGM abstracts the database and provides a convenient way to persist your domain model in the graph and query it without using low level drivers.
It also provides the flexibility to the developer to supply custom queries where the queries generated by Neo4j-OGM are insufficient.

[[introduction:ogm:introducing-ogm]]
=== Introducing the Neo4j-OGM

Developing Java Business Applications often requires mapping rich domain models to your database.
The Neo4j-OGM library is a pure Java library that can persist (annotated) domain objects using Neo4j.
It uses Cypher statements to handle those operations in Neo4j.

Neo4j-OGM supports tracking changes to minimize necessary updates and transitive persistence (reading and updating neighborhoods of an object).

The connection to Neo4j handled by a transport mode layer called driver, which can use the binary protocol, HTTP or Neo4j’s embedded APIs.

include::whats-new-ogm3.adoc[]

[[introduction:requirements]]
== Requirements

Neo4j-OGM 3.2.x at minimum, requires:

* JDK Version 8 and above.
* Neo4j Database 3.2.x and above.


[[introduction:additional-resources]]
== Additional Resources

[[introduction:additional-resources:metadata]]
=== Project metadata

* Version control - https://github.com/neo4j/neo4j-ogm
* Bug tracker - https://github.com/neo4j/neo4j-ogm/issues

[[introduction:additional-resources:help]]
=== Getting Help or providing feedback

If you encounter issues or you are just looking for advice, feel free to use one of the links below:

* Talk and share with the community on the https://neo4j-users.slack.com[SDN/OGM Slack channel]
* The https://github.com/neo4j-examples/neo4j-ogm-university[sample project:Neo4j-OGM University].
  This project is used in the <<tutorial:introduction,Tutorial>>.

* For more detailed questions, use our https://community.neo4j.com/c/drivers-stacks/spring-data-neo4j-ogm[community platform]
or http://stackoverflow.com/questions/tagged/neo4j-ogm[Neo4j-OGM on StackOverflow].
* Use the https://github.com/neo4j-examples/neo4j-sdn-ogm-issue-report-template[templates] for reporting issues (they can also be used to bootstrap your projects).

[[introduction:graph-database:introducing-neo4j:learn-more]]
==== Learning more

The jumping off ground for learning about Neo4j is https://neo4j.com/[neo4j.com].
Here is a list of other useful resources:

* The https://neo4j.com/docs/[Neo4j documentation] introduces Neo4j and contains links to getting started guides, reference documentation and tutorials.
* The https://neo4j.com/sandbox/[online sandbox] provides a convenient way to interact with a Neo4j instance in combination with the online https://neo4j.com//developer/get-started/[tutorial.]
* Neo4j https://neo4j.com/docs/driver-manual/current/[Java Bolt Driver].
* Several https://neo4j.com/books/[books] available for purchase and https://www.youtube.com/neo4j[videos] to watch.
