[[introduction:whats-new]]
== What's new in Neo4j-OGM 3 ?

At a high level, here is what has changed in this third major version of Neo4j-OGM :

* Simplified and less intrusive development model
+
Technical database ids were previously required in the domain model ; this is no more the case.
Ids can now be of any simple type, and generated using pluggable strategies.
To avoid confusion about where to place annotations, they are now only valid on class attributes.
See <<reference:annotating-entities:entity-identifier>> and <<migration>> for more details.

* Dynamic properties
+
This long awaited feature allows you to map node properties to dynamic structures (java maps).
See <<reference:annotating-entities:node-entity:dynamic-properties, Dynamic properties>>.

* Improved performance
+
Retrieving data is more performant in Neo4j-OGM 3, particularly for deep depths, because querying leverages
annotation information expressed in the domain model.
This allows to build smarter queries, and only fetch useful mappable data.

* More flexible configuration
+
OGM 3 offers rich configuration possibilities detailed <<reference:configuration, here>>.

* New baselines
+
The minimum required versions are Java 8 and Neo4j 3.1.

* Better integration with various execution environments
+
Internally, Neo4j-OGM 3 relies on https://github.com/lukehutch/fast-classpath-scanner[FastClasspathScanner] which
allows more reliable entity bytecode scanning, as well as better support application servers (like JBoss).

NOTE: Check the <<appendix:migration:checklist, migration checklist>> when upgrading from Neo4j-OGM 2.1
