[[reference_programming_model_mapping]]
= Object Graph Mapping

== Metadata collection
Reflection and annotation-based metadata is collected about persistent entities in `org.neo4j.ogm.metadata.Metadata`
which provides it to any part of the library. The information is stored in `ClassInfo` instances which hold all the
required object-graph mapping information for the type.  This metadata is discovered at start-up by specifying a
list of packages in which all classes are scanned, including those in sub-packages.  In order to omit a class from
being metadata-mapped you should annotate it with `@Transient`.

== The Session object
The Spring repositories and `Neo4jTemplate` are both backed by `org.neo4j.ogm.session.Session`, which is a key component
of the framework.  The Session provides methods to load, save or delete object graphs from the database and also
provides transaction support.  The new `Neo4jTemplate` is essentially a wrapper around this `Session`, which exposes
all of its useful methods but handles transactions and provides the traditional Spring Data operations.

==
Unlike the original AspectJ-driven mapping, Spring Data Neo4j 4 doesn't automatically commit when a
transaction closes, so an explicit call to `save(...)` is required in order to persist changes to the database.

== Fine-grained control
In terms of eager or lazy loading, the `depth` parameter may be specified to control the eagerness with which the object
graph is populated.  By default, loading an instance will map only its simple properties and its immediately-related
objects (horizon = 1), which helps to avoid accidentally loading the entire graph into memory.

When persisting changes to the model, the default depth is -1. This means that all affected objects in the entity model
that are reachable from the root object being persisted will be modified in the graph. You can change this depth to
any value, but you should not make the persistence depth


