[[reference_mapping]]
= Object Graph Mapping

Up until recently Spring Data Neo4j supported only the more advanced AspectJ based mapping approach. Feedback about issues with the AspectJ tooling and other implications persuaded us to add a simpler mapping (see <<reference_simple-mapping>>) to Spring Data Neo4j. Both versions work with similar annotations and provide similar APIs, but differ in behaviour.

Reflection and annotation-based metadata is collected about persistent entities in `org.neo4j.ogm.metadata.Metadata` which provides it to any part of the library. The information is stored in `ClassInfo` instances which hold all the required object-graph mapping information for the type.  This metadata is discovered at start-up by specifying a list of packages in which all classes are scanned, including those in sub-packages.  In order to omit a class from being metadata-mapped you should annotate it with `@Transient`.

The Spring repositories and `Neo4jTemplate` are both backed by `org.neo4j.ogm.session.Session`, which is a key component of the framework.  The Session provides methods to load, save or delete object graphs from the database and also provides transaction support.  The new `Neo4jTemplate` is essentially a wrapper around this `Session`, which exposes all of its useful methods but handles transactions and provides the traditional Spring Data operations.

Unlike the original AspectJ-driven mapping, Spring Data Neo4j 4 doesn't manage your entities within a transaction, so an explicit call to `Session.save(...)` is required in order to persist changes to the database.  Intuitively, this can be done directly or, preferably, via `Neo4jTemplate` or through a repository.

In terms of eager or lazy loading, the `depth` parameter may be specified to control the eagerness with which the object graph is populated.  By default, loading an instance will map only its simple properties and its immediately-related objects, which helps to avoid accidentally loading the entire graph into memory.


