= Neo4j OGM - An Object Graph Mapping Library for Neo4j
:toc:
:toc-placement!:
:revnumber: {version}
:revdate: {localdate}

Neo4j OGM Version 1.1.0 (June 2015)

(C) 2010-2015 Graph Aware Ltd - Neo Technology, Inc.

NOTE: Copies of this document may be made for your own use and for distribution to others, provided that you do not charge any fee
for such copies and further provided that each copy contains this Copyright Notice, whether distributed in print or electronically.

toc::[]

:leveloffset: +1

[[preface]]
= Preface
:leveloffset: +1

include::introduction/neo4j/neo4j.adoc[]

:leveloffset: -1

<<<
[[tutorial]]
= Tutorial

The first part of this guide is a tutorial that takes the reader through steps necessary to get started with the  Neo4j OGM.
Neo4j OGM will power a web application that allows you to manage a College's Departments, Teaching Staff, Subjects, Students and Classes.

The complete source code for the application is available on https://github.com/neo4j-examples/neo4j-ogm-university[Github].

:leveloffset: +1

include::tutorial/intro.adoc[]

<<<

include::tutorial/model.adoc[]

<<<

include::tutorial/ogm.adoc[]

<<<

include::tutorial/annotations.adoc[]

<<<

include::tutorial/session.adoc[]

<<<

include::tutorial/conclusion.adoc[]

:leveloffset: -1


<<<

[[reference]]
= Reference Documentation

This part of the guide provides the reference documentation for the Neo4j OGM.

Its content covers information about the programming model, APIs, concepts, annotations and technical details of the
Neo4j OGM.

Whenever you look for the means to employ the full power of the OGM library, you should be able to find
your answers in this reference section. If you don't, please inform us about missing or incorrect content.

:leveloffset: +1

include::reference/preface.adoc[]

<<<

include::reference/setup.adoc[]

<<<

include::reference/programming-model/programming-model.adoc[]

:leveloffset: -1

