[[reference_preface]]
= Reference Documentation

== Spring Data and Spring Data Neo4j

http://springsource.org/spring-data[Spring Data] is a SpringSource project that aims to provide Spring's convenient
programming model and well known conventions for NOSQL databases. Currently there is support for graph (Neo4j),
key-value (Redis, Riak), document (MongoDB) and relational (Oracle) databases.

The Spring Data Neo4j project, as part of the Spring Data initiative, aims to simplify development with the Neo4j graph
database. Like JPA, it uses annotations on simple POJO domain objects. Together with metadata, the annotations drive
mapping the POJO entities and their fields to nodes, relationships, and properties in the graph database.

For version 4, Spring Data Neo4j has been rewritten from scratch to natively support Neo4j deployments in standalone server mode. It uses Cypher, the Neo4j query language, and the HTTP protocol to communicate with the database.  It's therefore worth noting that there *may be some backward compatibility issues* when migrating to version 4, so be sure to check the <<reference_migration,migration guide>> to avoid any unwanted surprises.

For integration of Neo4j and other languages, please see http://neo4j.com/developer/language-guides/[Language Guides].

== Reference Documentation Overview

The explanation of Spring Data Neo4j's programming model starts with some underlying details. The basic concepts of
the Object-Graph Mapping (OGM) library used by Spring Data Neo4j internally, is explained in the initial chapter.

To get started with a simple application, you need only your domain model and (optionally) the annotations
(see <<reference_programming-model_annotations>>) provided by the library. You use annotations to mark domain objects
to be reflected by nodes and relationships of the graph database. For individual fields the annotations allow you to
declare how they should be processed and mapped to the graph. For property fields and references to other entities this
is straightforward.

To use advanced functionality like Cypher queries, a basic understanding of the graph data model is required. The graph
data model is explained in the chapter about Neo4j, see <<neo4j>>.

Relationships between entities are first class citizens in a graph database and therefore worth a separate chapter
(<<reference_programming_model:relationships>>) describing their usage in Spring Data Neo4j.

Spring Data Commons provides a very powerful repository infrastructure that is also leveraged in Spring Data Neo4j.
Those repositories consist only of a composition of interfaces that declare the available functionality in each repository.
The implementation details of commonly used persistence methods are handled by the library. At least for typical CRUD and
query-operations that is very convenient. The repositories are extensible by annotated, named or derived finder methods.
For custom implementations of repository methods you are free to add your own code. (<<reference_programming-model_repositories>>).

Being a Spring Data library, Spring Data Neo4j offers a comprehensive `Neo4jTemplate` (<<reference_template>>) for interacting with the mapped entities and the Neo4j graph database.  As of version 4, `Neo4jTemplate` is based on an `org.neo4j.ogm.session.Session` object, which also provides the basis on which the Spring Data Neo4j Repositories are based. 

Because Neo4j is a schema-free database, Spring Data Neo4j uses a sophisticated mechanism to map Java types to Neo4j nodes
using labels. How that works is explained here: <<reference_programming-model_typerepresentationstrategy>>.

Using computed fields that are dynamically backed by graph operations is a bit more involved. First you should know about
Cypher queries. Those are explained in <<neo4j>>. Then you can start using virtual, computed fields in your entities
<<reference_programming-model_projection>> .

Neo4j uses transactions to guarantee the integrity of your data and Spring Data Neo4j supports this fully. The implications of this are described in the chapter around transactions. (<<reference_programming-model_transactions>>)

The Spring configuration boils down to two lines of `<spring-neo4j>` namespace setup. (see <<setup>>)

The provided samples, which are also publicly hosted on http://spring.neo4j.org/examples[Github], are explained in <<reference_samples>>.

The performance implications of using Spring Data Neo4j are detailed in <<reference_performance>>. This chapter also discusses which use cases should not be handled with Spring Data Neo4j.
