[[setup]]
= Getting started

Spring Data Neo4j dramatically simplifies development, but some setup is naturally required. For building the
application, Maven needs to be configured to include the Spring Data Neo4j dependencies and
after the build setup is complete, the Spring application needs to be configured to make use of Spring Data Neo4j.
Examples for these different setups can be found in the http://spring.neo4j.org/examples[Spring Data Neo4j examples].

Spring Data Neo4j projects can be built using Maven, Gradle or Ant/Ivy.

== Dependencies for Spring Data Neo4j

.Maven dependencies for Spring Data Neo4j
====
[source,xml]
----
        <dependency>
            <groupId>org.springframework.data</groupId>
            <artifactId>neo4j-spring</artifactId>
        </dependency>
----
====


== Spring configuration

Users of Spring Data Neo4j 4 can current only configure their applications using Java-based bean configuration. Support
for XML namespace configuration is expected to be available in Milestone 2

=== Java-based bean configuration

In order to configure Spring Data Neo4j with Java-based bean config, your Spring context must extend the core
`Neo4jConfiguration` context that comes with Spring Data Neo4j. The example below shows how this can be done.

NOTE:   You will need to override the `neo4jServer()`, `getSessionFactory()` and `getSession()` bean definitions to provide
the required context for your own application. This is explained in more detail below.

.Pure Java bean configuration
====
[source,java]
----
@Configuration
@EnableNeo4jRepositories(basePackages = "org.neo4j.example.repository")
@EnableTransactionManagement
public class Application extends Neo4jConfiguration {

    @Override
    @Bean
    public Neo4jServer neo4jServer() {
        return new RemoteServer("http://localhost:7474");
    }

    @Override
    @Bean
    public SessionFactory getSessionFactory() {
        return new SessionFactory("org.neo4j.example.domain");
    }

    @Override
    @Bean
    @Scope(value = "session", proxyMode = ScopedProxyMode.TARGET_CLASS)
    public Session getSession() throws Exception {
        return super.getSession();
    }

}
----
====

=== Neo4jServer bean


=== SessionFactoryBean


=== Session Bean


Additional beans can be configured to be included in the Neo4j-Configuration just by defining them in the
Spring context in the normal way.
