[[reference:annotating-entities]]
= Annotating Entities


[[reference:annotating-entities:node-entity]]
== @NodeEntity: The basic building block

The `@NodeEntity` annotation is used to declare that a POJO class is an entity backed by a node in the graph database.
Entities handled by Neo4j-OGM must have one empty public constructor to allow the library to construct the objects.

Fields on the entity are by default mapped to properties of the node.
Fields referencing other node entities (or collections thereof) are linked with relationships.

`@NodeEntity` annotations are inherited from super-types and interfaces.
It is not necessary to annotate your domain objects at every inheritance level.

Entity fields can be annotated with annotations like `@Property`, `@Id`, `@GeneratedValue`, `@Transient` or `@Relationship`.
All annotations live in the `org.neo4j.ogm.annotation` package.
Marking a field with the transient modifier has the same effect as annotating it with `@Transient`; it won't be persisted to the graph database.

.Persisting an annotated entity
[source, java]
----
@NodeEntity
public class Actor extends DomainObject {

   @Id @GeneratedValue
   private Long id;

   @Property(name="name")
   private String fullName;

   @Property("age") // using value attribute to have a shorter definition
   private int age;

   @Relationship(type="ACTED_IN", direction=Relationship.Direction.OUTGOING)
   private List<Movie> filmography;

}

@NodeEntity(label="Film")
public class Movie {

   @Id @GeneratedValue Long id;

   @Property(name="title")
   private String name;

}
----

The default label is the simple class name of the annotated entity.
There are some rules to determine if parent classes also contribute their label to the child class:

* the parent class is a non-abstract class (the existing of `@NodeEntity` is optional)
* the parent class is an abstract class and has a `@NodeEntity` annotation
* `java.lang.Object` will be ignored
* interfaces do not create an additional label

If the `label` (as you can see in the example above) or the `value` attribute of the `@NodeEntity` annotation is set it will replace the default label applied to the node in the database.

Saving a simple object graph containing one actor and one film using the above annotated objects would result in the following being persisted in Neo4j.

[source, cypher]
----
(:Actor:DomainObject {name:'Tom Cruise'})-[:ACTED_IN]->(:Film {title:'Mission Impossible'})
----

When annotating your objects, you can choose to NOT apply the annotations on the fields.
OGM will then use conventions to determine property names in the database for each field.

.Persisting a non-annotated entity
[source, java]
----
public class Actor extends DomainObject {

   private Long id;
   private String fullName;
   private List<Movie> filmography;

}

public class Movie {

   private Long id;
   private String name;

}
----

In this case, a graph similar to the following would be persisted.

[source, cypher]
----
(:Actor:DomainObject {fullName:'Tom Cruise'})-[:FILMOGRAPHY]->(:Movie {name:'Mission Impossible'})
----

While this will map successfully to the database, it's important to understand that the names of the properties and relationship types are tightly coupled to the class's member names.
Renaming any of these fields will cause parts of the graph to map incorrectly, hence the recommendation to use annotations.

Please read <<reference:annotating-entities:non-annotated-properties>> for more details and best practices on this.

[[reference:annotating-entities:node-entity:dynamic-properties]]
=== @Properties: dynamically mapping properties to graph


A `@Properties` annotation tells Neo4j-OGM to map values of a Map field in a node or relationship entity to properties of
a node or a relationship in the graph.

The property names are derived from field name or `prefix`, `delimiter` and keys in the Map.
For example Map field with name `address` containing following entries:

[source]
----
"street" => "Downing Street"
"number" => 10
----

will map to following node/relationship properties

[source]
----
address.street=Downing Street
address.number=10
----

Supported types for keys in the `Map` are `String` and `Enum`.

The values in the `Map` can be of any Java type equivalent to Cypher types.
If full type information is provided other Java types are also supported.

If annotation parameter `allowCast` is set to true then types that can be cast to corresponding Cypher types are allowed as well.
[NOTE]
The original type cannot be deduced and the value will be deserialized to corresponding type - e.g.
when Integer instance is put to `Map<String, Object>` it will be deserialized as `Long`.

[source, java]
----
@NodeEntity
public class Student {

    @Properties
    private Map<String, Integer> properties = new HashMap<>();

    @Properties
    private Map<String, Object> properties = new HashMap<>();

}
----




[[reference:annotating-entities:node-entity:runtime-managed-labels]]
=== Runtime managed labels

As stated above, the label applied to a node is the contents of the `@NodeEntity` label property, or if not specified, it will default to the simple class name of the entity.
Sometimes it might be necessary to add and remove additional labels to a node at _runtime_.
We can do this using the `@Labels` annotation.
Let's provide a facility for adding additional labels to the `Student` entity:

[source, java]
----
@NodeEntity
public class Student {

    @Labels
    private List<String> labels = new ArrayList<>();

}
----

Now, upon save, the node's labels will correspond to the entity's class hierarchy _plus_ whatever the contents of the backing field are.
We can use one `@Labels` field per class hierarchy - it should be exposed or hidden from sub-classes as appropriate.

Runtime labels must not conflict with static labels defined on node entities.

[NOTE]
In a typical situation Neo4j-OGM issues one request per node entity type when saving node entities to the database.
Using many distinct labels will result into many requests to the database (one request per unique combination of labels).


[[reference:annotating-entities:relationship]]
== @Relationship: Connecting node entities

Every field of an entity that references one or more other node entities is backed by relationships in the graph.
These relationships are managed by Neo4j-OGM automatically.

The simplest kind of relationship is a single object reference pointing to another entity (1:1).
In this case, the reference does not have to be annotated at all, although the annotation may be used to control the direction and type of the relationship.
When setting the reference, a relationship is created when the entity is persisted.
If the field is set to `null`, the relationship is removed.

.Single relationship field
[source, java]
----
@NodeEntity
public class Movie {
    ...
    private Actor topActor;
}
----

It is also possible to have fields that reference a set of entities (1:N).
Neo4j-OGM supports the following types of entity collections:

* `java.util.Vector`
* `java.util.List`, backed by a `java.util.ArrayList`
* `java.util.SortedSet`, backed by a `java.util.TreeSet`
* `java.util.Set`, backed by a `java.util.HashSet`
* Arrays

.Node entity with relationships
[source, java]
----
@NodeEntity
public class Actor {
    ...
    @Relationship(type = "TOP_ACTOR", direction = Relationship.Direction.INCOMING)
    private Set<Movie> topActorIn;

    @Relationship("ACTS_IN") // same meaning as above but using the value attribute
    private Set<Movie> movies;
}
----

For graph to object mapping, the automatic transitive loading of related entities depends on the depth of the horizon specified on the call to `Session.load()`.
The default depth of 1 implies that _related_ node or relationship entities will be loaded and have their properties set, but none of their related entities will be populated.

If this `Set` of related entities is modified, the changes are reflected in the graph once the root object (`Actor`, in this case) is saved.
Relationships are added, removed or updated according to the differences between the root object that was loaded and the corresponding one that was saved..

Neo4j-OGM ensures by default that there is only one relationship of a given type between any two given entities.
The exception to this rule is when a relationship is specified as either `OUTGOING` or `INCOMING` between two entities of the same type.
In this case, it is possible to have two relationships of the given type between the two entities, one relationship in either direction.

If you don't care about the direction then you can specify `direction=Relationship.Direction.UNDIRECTED` which will guarantee that the path between two node entities is navigable from either side.

For example, consider the `PARTNER` relationship between two companies, where `(A)-[:PARTNER_OF]->(B)` implies `(B)-[:PARTNER_OF]->(A)`.
The direction of the relationship does not matter; only the fact that a `PARTNER_OF` relationship exists between these two companies is of importance.
Hence an `UNDIRECTED` relationship is the correct choice, ensuring that there is only one relationship of this type between two partners and navigating between them from either entity is possible.

[NOTE]
====
The direction attribute on a `@Relationship` defaults to `OUTGOING`.
Any fields or methods backed by an `INCOMING` relationship must be explicitly annotated with an `INCOMING` direction.
====

[[reference:annotating-entities:relationship:type-discrimination]]
=== Using more than one relationship of the same type

In some cases, you want to model two different aspects of a conceptual relationship using the same relationship type.
Here is a canonical example:

.Clashing Relationship Type
[source,java]
----
@NodeEntity
class Person {
    private Long id;
    @Relationship(type="OWNS")
    private Car car;

    @Relationship(type="OWNS")
    private Pet pet;
...
}
----

This will work just fine, however, please be aware that this is only because the end node types (Car and Pet) are different types.
If you wanted a person to own two cars, for example, then you'd have to use a `Collection` of cars or use differently-named relationship types.

[[reference:annotating-entities:relationship:ambiguity]]
=== Ambiguity in relationships

In cases where the relationship mappings could be ambiguous, the recommendation is that:

* The objects be navigable in both directions.
* The `@Relationship` annotations are explicit.

Examples of ambiguous relationship mappings are multiple relationship types that resolve to the same types of entities, in a given direction, but whose domain objects are not navigable in both directions.

=== Ordering

Neo4j doesn't have any ordering on relationships, so the relationships are fetched without any specific ordering.
If you want to impose order on collections of relationships you have several options:

- use a `SortedSet` and implement `Comparable`
- sort relationships in <<reference:annotating-entities:postload, `@PostLoad`>> annotated method

You can sort either by a property of a related node or by relationship property.
To sort by relationship property you need to use a relationship entity.
See <<reference:annotating-entities:relationship-entity>>.

[[reference:annotating-entities:relationship-entity]]
== @RelationshipEntity: Rich relationships

To access the full data model of graph relationships, POJOs can also be annotated with `@RelationshipEntity`, making them relationship entities.
Just as node entities represent nodes in the graph, relationship entities represent relationships.
Such POJOs allow you to access and manage properties on the underlying relationships in the graph.

Fields in relationship entities are similar to node entities, in that they're persisted as properties on the relationship.
For accessing the two endpoints of the relationship, two special annotations are available: `@StartNode` and `@EndNode`.
A field annotated with one of these annotations will provide access to the corresponding endpoint, depending on the chosen annotation.

For controlling the relationship-type a `String` attribute called `type` is available on the `@RelationshipEntity` annotation.
Like the simple strategy for labelling node entities, if this is not provided then the name of the class is used to derive the relationship type,
although it's converted into SNAKE_CASE to honour the naming conventions of Neo4j relationships.
As of the current version of Neo4j-OGM, the `type` *must* be specified on the `@RelationshipEntity` annotation as well as its corresponding `@Relationship` annotations.
This can also be done without naming the attribute but only providing the value.


[NOTE]
====
You must include `@RelationshipEntity` plus exactly one `@StartNode` field and one `@EndNode` field on your relationship entity classes or Neo4j-OGM will throw a MappingException when reading or writing.
It is not possible to use relationship entities in a non-annotated domain model.
====

.A simple Relationship entity
[source,java]
----
@NodeEntity
public class Actor {
    Long id;
    @Relationship(type="PLAYED_IN") private Role playedIn;
}

@RelationshipEntity(type = "PLAYED_IN")
public class Role {
    @Id @GeneratedValue   private Long relationshipId;
    @Property  private String title;
    @StartNode private Actor actor;
    @EndNode   private Movie movie;
}

@NodeEntity
public class Movie {
    private Long id;
    private String title;
}
----

Note that the `Actor` also contains a reference to a `Role`.
This is important for persistence, *even when saving the `Role` directly*, because paths in the graph are written starting with nodes first and then relationships are created between them.
Therefore, you need to structure your domain models so that relationship entities are reachable from node entities for this to work correctly.

Additionally, Neo4j-OGM will not persist a relationship entity that doesn't have any properties defined.
If you don't want to include properties in your relationship entity then you should use a plain `@Relationship` instead.
Multiple relationship entities which have the same property values and relate the same nodes are indistinguishable from each other and are represented as a single relationship by Neo4j-OGM.

[NOTE]
====
The `@RelationshipEntity` annotation must appear on all leaf subclasses if they are part of a class hierarchy representing relationship entities.
This annotation is optional on superclasses.
====

=== A note on JSON serialization

Looking at the example given above the circular dependency on the class level between the node and the rich relationship can easily be spotted.
It will not have any effect on your application as long as you do not serialize the objects.
One kind of serialization that is used today is JSON serialization using the Jackson mapper.
This mapper library is often used in connection with other frameworks like Spring or Java EE and their corresponding web modules.
Traversing the object tree it will hit the part when it visits a `Role` after visiting an `Actor`.
Obvious it will then find the `Actor` object and visit this again, and so on.
This will end up in a `StackOverflowError`.
To break this parsing cycle it is mandatory to support the mapper by providing annotation to your class(es).
This can be done by adding either `@JsonIgnore` on the property that causes the loop or `@JsonIgnoreProperties`.


.Suppress infinite traversing
[source,java]
----
@NodeEntity
public class Actor {
    Long id;

    // Needs knowledge about the attribute "title" in the relationship.
    // Applying JsonIgnoreProperties like this ignores properties of the attribute itself.
    @JsonIgnoreProperties("actor")
    @Relationship(type="PLAYED_IN") private Role playedIn;
}

@RelationshipEntity(type="PLAYED_IN")
public class Role {
    @Id @GeneratedValue private Long relationshipId;
    @Property private String title;

    // Direct way to suppress the serialization.
    // This ignores the whole actor attribute.
    @JsonIgnore
    @StartNode private Actor actor;

    @EndNode   private Movie movie;
}

----


[[reference:annotating-entities:entity-identifier]]
== Entity identifier

Every node and relationship persisted to the graph must have an ID.
Neo4j-OGM uses this to identify and re-connect the entity to the graph in memory.
Identifier may be either a primary id or a native graph id (_the technical id attributed by Neo4j at node creation time_).

For primary id use the `@Id` on a field of any supported type or a field with provided `AttributeConverter`.
A unique index is created for such property (if index creation is enabled).
User code should either set the id manually when the entity instance is created or id generation strategy should be used.
It is not possible to store an entity with null id value and no generation strategy.
[NOTE]
====
Specifying primary id on a relationship entity is possible, but lookups by this id are slow, because Neo4j database doesn't support schema indexes on relationships.
====

For native graph id use `@Id @GeneratedValue` (with default strategy `InternalIdStrategy`).
The field type must be `Long`.
This id is assigned automatically upon saving the entity to the graph and user code should _never_ assign a value to it.

[NOTE]
====
It must not be a primitive type because then an object in a transient state cannot be represented, as the default value 0 would point to the reference node.
====

[WARNING]
====
***Do not*** rely on this ID for long running applications.
Neo4j will reuse deleted node ID's. It is recommended users come up with their own unique identifier for their domain objects (or use a UUID).
====

An entity can be looked up by this either type of id by using `Session.load(Class<T>, ID)` and `Session.loadAll(Class<T>, Collection<ID>)` methods.

It is possible to have both natural and native id in one entity.
In such situation lookups prefer the primary id.

If the field of type `Long` is simply named 'id' then it is not necessary to annotate it with `@Id @GeneratedValue` as Neo4j-OGM will use it automatically as native id.

[[reference:annotating-entities:graph-id:equality]]
=== Entity Equality

Entity equality can be a grey area.
There are many debatable issues, such as whether natural keys or database identifiers best describe equality and the effects of versioning over time.
Neo4j-OGM does not impose a dependency upon a particular style of `equals()` or `hashCode()` implementation.
The native or custom id field are directly checked to see if two entities represent the same node and a 64-bit hash code is used for dirty checking, so you're not forced to write your code in a certain way!

[WARNING]
You should write your `equals` and `hashCode` in a domain specific way for managed entities. *We strongly advise developers to not use the native id described by a `Long` field in combination with `@Id @GeneratedValue` in these methods*.
This is because when you first persist an entity, its hashcode changes because Neo4j-OGM populates the database ID on save.
This causes problems if you had inserted the newly created entity into a hash-based collection before saving.

=== Id Generation Strategy

If the `@Id` annotation is used on its own it is expected that the field will be set by the application code.
To automatically generate and assign a value of the property the annotation `@GeneratedValue` can be used.

The `@GeneratedValue` annotation has optional parameter `strategy`, which can be used to provide a custom id generation strategy.
The class must implement `org.neo4j.ogm.id.IdStrategy` interface.
The strategy class can either supply no argument constructor - in which case Neo4j-OGM will create an instance of the strategy and call it.
For situations where some external context is needed an externally created instance can be registered with SessionFactory by using
`SessionFactory.register(IdStrategy)`.

[[reference:annotating-entities:version]]
== Optimistic locking with @Version annotation

Optimistic locking is supported by Neo4j-OGM to provide concurrency control.
To use optimistic locking define a field annotated with `@Version` annotation.
The field is then managed by Neo4j-OGM and used to perform optimistic locking checks when updating entities.
The type of the field must be `Long` and an entity may contain only one such field.

Typical scenario where optimistic locking is used then looks like follows:

* new object is created, version field contains `null` value
* when the object is saved the version field is set to 0 by Neo4j-OGM
* when a modified object is saved the version provided in the object is checked against a version in the database
during the update, if successful then the version is incremented both in the object and in the database
* if another transaction modified the object in the meantime (and therefore incremented the version)
then this is detected and an `OptimisticLockingException` is thrown

Optimistic locking check is performed for

* updating properties of nodes and relationship entities
* deleting nodes via `Session.delete(T)`
* deleting relationship entities via `Session.delete(T)`
* deleting relationship entities detected through `Session.save(T)`

When an optimistic locking failure happens following operations are performed on the Session:

* object which failed the optimistic locking check is removed from the context so it can be reloaded
* in case a default transaction is used it is rolled back
* in case a manual transaction is used then it is *not* rolled back, but because the update may contain multiple
statements which are checked eagerly it is not defined what updates were actually performed in the database and it is
advised to rollback the transaction.
If you know you updates consists of single modification you may however choose to reload the object and continue the transaction.

[[reference:annotating-entities:property]]
== @Property: Optional annotation for property fields

As we touched on earlier, it is not necessary to annotate property fields as they are persisted by default.
Fields that are annotated as `@Transient` or with `transient` are exempted from persistence.
All fields that contain primitive values are persisted directly to the graph.
All fields convertible to a `String` using the conversion services will be stored as a string.
Neo4j-OGM includes default type converters for commonly used types, for a full list see <<reference:type-conversion:built-in>>.

Custom converters are also specified by using `@Convert` - this is discussed in detail <<reference:type-conversion:custom, later on>>.

Collections of primitive or convertible values are stored as well.
They are converted to arrays of their type or strings respectively.

Node property names can be explicitly assigned by setting the `name` attribute.
For example `@Property(name="last_name") String lastName`.
The node property name defaults to the field name when not specified.

[NOTE]
====
Property fields to be persisted to the graph must not be declared `final`.
====

[[reference:annotating-entities:postload]]
== @PostLoad

A method annotated with `@PostLoad` will be called once the entity is loaded from the database.

[[reference:annotating-entities:non-annotated-properties]]
== Non-annotated properties and best practices

Neo4j-OGM supports mapping annotated and non-annotated objects models.
It's possible to save any POJO without annotations to the graph, as the framework applies conventions to decide what to do.
This is useful in cases when you don't have control over the classes that you want to persist.
The recommended approach, however, is to use annotations wherever possible, since this gives greater control and means that code can be refactored safely without risking breaking changes to the labels and relationships in your graph.

NOTE: The support for non-annotated domain classes might be dropped in the future, to allow startup optimizations.

Annotated and non-annotated objects can be used within the same project without issue.

The object graph mapping comes into play whenever an entity is constructed from a node or relationship.
This could be done explicitly during the lookup or create operations of the `Session` but also implicitly while executing any graph operation that returns nodes or relationships and expecting mapped entities to be returned.

Entities handled by Neo4j-OGM must have one empty public constructor to allow the library to construct the objects.

Unless annotations are used to specify otherwise, the framework will attempt to map any of an object's "simple" fields to node properties and any rich composite objects to related nodes.
A "simple" field is any primitive, boxed primitive or String or arrays thereof, essentially anything that naturally fits into a Neo4j node property.
For related entities the type of a relationship is inferred by the bean property name.
