[[reference:configuration]]
= Configuration

[[reference:configuration:method]]
== Configuration method

There are several ways to supply configuration to Neo4j-OGM:

- using a properties file
- programmatically using Java
- by providing an already configured Neo4j Java driver instance

These methods are described below.
They are also available as code in the <<introduction:additional-resources:help, examples>>.

[[reference:configuration:method:properties]]
=== Using a properties file

Properties file on classpath:

[source, java]
----
ConfigurationSource props = new ClasspathConfigurationSource("my.properties");
Configuration configuration = new Configuration.Builder(props).build();
----

Properties file on filesystem:

[source, java]
----
ConfigurationSource props = new FileConfigurationSource("/etc/my.properties");
Configuration configuration = new Configuration.Builder(props).build();
----


[[reference:configuration:method:java]]
=== Programmatically using Java

In cases where you are not be able to provide configuration via a properties file you can configure Neo4j-OGM programmatically instead.

The `Configuration` object provides a fluent API to set various configuration options.
This object then needs to be supplied to the `SessionFactory` constructor in order to be configured.

=== By providing a Neo4j driver instance

Just configure the driver as you would do for direct access to the database, and pass the driver instance to the session factory.

This method allows the greatest flexibility and gives you access to the full range of low level configuration options.

.Example providing a bolt driver instance to Neo4j-OGM
[source, java]
----
org.neo4j.driver.Driver nativeDriver = ...;
Driver ogmDriver = new BoltDriver(nativeDriver);
new SessionFactory(ogmDriver, ...);
----

[[reference:configuration:driver]]
== Driver Configuration

For configuration through properties file or configuration builder the driver is automatically inferred from given URI.
Empty URI means embedded driver with impermanent database.

[[reference:configuration:driver:http]]
=== HTTP Driver


.Basic HTTP Driver Configuration
[%autowidth.spread,frame="topbot",options="header"]
|======================
|ogm.properties   | Java Configuration

a|
[source, properties]
----
URI=http://user:password@localhost:7474
----

a|
[source, java]
----
Configuration configuration = new Configuration.Builder()
        .uri("http://user:password@localhost:7474")
        .build()
----
|======================

[[reference:configuration:driver:bolt]]
=== Bolt Driver


Note that for the `URI`, if no port is specified, the default Bolt port of `7687` is used.
Otherwise, a port can be specified with `bolt://neo4j:password@localhost:1234`.

Also, the bolt driver allows you to define a connection pool size, which refers to the maximum number of sessions per URL.
This property is optional and defaults to `50`.

.Basic Bolt Driver Configuration
[%autowidth.spread,frame="topbot",options="header"]
|======================
|ogm.properties   | Java Configuration

a|
[source, properties]
----
URI=bolt://neo4j:password@localhost
connection.pool.size=150
----

a|
[source, java]
----
Configuration configuration = new Configuration.Builder()
        .uri("bolt://neo4j:password@localhost")
        .setConnectionPoolSize(150)
        .build()
----
|======================

A timeout to the database with the Bolt driver can be set by updating your Database's `neo4j.conf`.
The exact setting to change can be http://neo4j.com/docs/operations-manual/current/reference/configuration-settings/#config_dbms.transaction.timeout[found here].

[[reference:configuration:driver:embedded]]
=== Embedded Driver


You should use the Embedded driver if you don't want to use a client-server model, or if your application is running as a Neo4j Unmanaged Extension.
You can specify a permanent data store location to provide durability of your data after your application shuts down, or you can use an impermanent data store, which will only exist while your application is running.

[NOTE]
As of 2.1.0 the Neo4j-OGM embedded driver no longer ships with the Neo4j kernel.
Users are expected to provide this dependency through their dependency management system.
See <<reference:getting-started, Getting Started>> for more details.

.Permanent Data Store Embedded Driver Configuration
[%autowidth.spread,frame="topbot",options="header"]
|======================
|ogm.properties   | Java Configuration

a|
[source, properties]
----
URI=file:///var/tmp/neo4j.db
----

a|
[source, java]
----
Configuration configuration = new Configuration.Builder()
             .uri("file:///var/tmp/neo4j.db")
             .build()
----
|======================

To use an impermanent data store which will be deleted on shutdown of the JVM, you just omit the URI attribute.


.Impermanent Data Store Embedded Driver Configuration
[%autowidth.spread,frame="topbot",options="header"]
|======================
|ogm.properties   | Java Configuration

a|
[source, properties]
----
# Leave empty
----

a|
[source, java]
----
Configuration configuration = new Configuration.Builder().build()
----
|======================


[[reference:configuration:driver:embedded:neo4j-config]]
==== Configuration of the embedded instance

The embedded instance of Neo4j can be configured through a standard `neo4j.conf` file.
A `neo4j.conf` file is a properties based configuration format.
Neo4j's available configuration properties are listed in the http://neo4j.com/docs/operations-manual/current/reference/configuration-settings/[product manual].
Not all of them are applicable to an embedded scenario.

You can pass the location of a configuration file either through `ogm.properties` or programmatically.
Both file and classpath-resources are supported.
Resource location without a protocol prefix are assumed to be classpath resources.

.Providing the location of a Neo4j configuration file
[%autowidth.spread,frame="topbot",options="header"]
|======================
|ogm.properties   | Java Configuration

a|
[source, properties]
----
# Looks in the root of the classpath
neo4j.conf.location=neo4j.conf

# Explicitly in the classpath
# neo4j.conf.location=classpath:neo4j.conf

# Or as file URL
# neo4j.conf.location=file:///config/neo4j.conf
----

a|
[source, java, indent=0]
----
String neo4jConfLocation;

​// Choose one:
​// Looks in the root of the classpath
neo4jConfLocation = "neo4j.conf"

​// Explicitly in the classpath
​// neo4jConfLocation = "classpath:neo4j.conf"

​// Or as file URL
​// neo4jConfLocation = "file:///config/neo4j.conf"

Configuration configuration =
    new Configuration.Builder()
        .neo4jConfLocation(neo4jConfLocation)
        .build();
----
|======================

[WARNING]
By setting `dbms.config=HA` in the configuration file for Neo4j, you can enable HA mode of the embedded instance.
You need to have the required enterpris dependencies on the classpath.
For Neo4j 3.4 those are `org.neo4j:neo4j-ha` and `org.neo4j:neo4j-enterprise`, for 3.5 it's only `com.neo4j:neo4j-enterprise`.


[[reference:configuration:driver:embedded:unmanaged]]
==== Configuration of an unmanaged extension

The `OgmPluginInitializer` class was deprecated in Neo4j-OGM 3.2 and will be removed in the next major version.
To use Neo4j-OGM within an unmanaged extension you connect to the database the usual way you would do with an embedded driver.


[[reference:configuration:driver:credentials]]
=== Credentials

If you are using the HTTP or Bolt Driver you have a number of different ways to supply credentials to the Driver Configuration.

[%autowidth.spread,frame="topbot",options="header"]
|======================
|ogm.properties   | Java Configuration

a|
[source, properties]
----
# embedded
URI=http://user:password@localhost:7474

# separately
username="user"
password="password"
----

a|
[source, java]
----
// embedded
Configuration configuration = new Configuration.Builder()
             .uri("bolt://user:password@localhost")
             .build()

// separately as plain text
Configuration configuration = new Configuration.Builder()
             .credentials("user", "password")
             .build()
----
|======================

_Note: Currently only Basic Authentication is supported by Neo4j-OGM.
If you need to use more advanced authentication scheme, use the native driver configuration method._

[[reference:configuration:driver:tsl]]
=== Transport Layer Security (TLS/SSL)

The Bolt and HTTP drivers also allow you to connect to Neo4j over a secure channel.
These rely on Transport Layer Security (aka TLS/SSL) and require the installation of a signed certificate on the server.

In certain situations (e.g. some cloud environments) it may not be possible to install a signed certificate even though you still want to use an encrypted connection.

To support this, both drivers have configuration settings allowing you to bypass certificate checking, although they differ in their implementation.

[NOTE]
Both of these strategies leave you vulnerable to a MITM attack.
You should probably not use them unless your servers are behind a secure firewall.

[[reference:configuration:driver:security:bolt]]
==== Bolt

[%autowidth.spread,frame="topbot",options="header"]
|======================
|ogm.properties   | Java Configuration

a|
[source, properties]
----
#Encryption level (TLS), optional, defaults to REQUIRED.
#Valid values are NONE,REQUIRED
encryption.level=REQUIRED

#Trust strategy, optional, not used if not specified.
#Valid values are TRUST_ON_FIRST_USE,TRUST_SIGNED_CERTIFICATES
trust.strategy=TRUST_ON_FIRST_USE

#Trust certificate file, required if trust.strategy is specified
trust.certificate.file=/tmp/cert
----

a|
[source, java]
----
Configuration config = new Configuration.Builder()
    ...
    .encryptionLevel("REQUIRED")
    .trustStrategy("TRUST_ON_FIRST_USE")
    .trustCertFile("/tmp/cert")
    .build();
----
|======================


`TRUST_ON_FIRST_USE` means that the Bolt Driver will trust the first connection to a host to be safe and intentional.
On subsequent connections, the driver will verify that the host is the same as on that first connection.

[[reference:configuration:driver:bolt]]
==== HTTP

[%autowidth.spread,frame="topbot",options="header"]
|======================
|ogm.properties   | Java Configuration

a|
[source, properties]
----
trust.strategy = ACCEPT_UNSIGNED
----

a|
[source, java]
----
Configuration configuration = new Configuration.Builder()
        .trustStrategy("ACCEPT_UNSIGNED")
        .build()
----
|======================


The `ACCEPT_UNSIGNED` strategy permits the HTTP Driver to accept Neo4j's default `snakeoil.cert` (and any other) unsigned certificate when connecting over HTTPS.


[[reference:configuration:driver:connection-test]]
=== Bolt connection testing

In order to prevent some network problems while accessing a remote database, you may want to tell the Bolt driver to test
connections from the connection pool.

This is particularly useful when there are firewalls between the application tier and the database.

You can do that with the connection liveness parameter which indicates the interval at which the connections will be tested.
A value of 0 indicates that the connection will always be tested.
A negative value indicates that the connection will never be tested.

[%autowidth.spread,frame="topbot",options="header"]
|======================
|ogm.properties   | Java Configuration

a|
[source, properties]
----
# interval, in milliseconds, to check for stale db connections (test-on-borrow)
connection.liveness.check.timeout=1000
----

a|
[source, java]
----
Configuration config = new Configuration.Builder()
    ...
    .connectionLivenessCheckTimeout(1000)
    .build();
----
|======================

=== Eager connection verification

OGM by default does not connect to Neo4j server on application startup.
This allows you to start the application and database independently and Neo4j will be accessed on first read/write.
To change this behaviour set the property `verify.connection` (or `Builder.verifyConnection(boolean)`) to true.
This settings is valid only for Bolt and HTTP drivers.

[[reference:configuration:logging]]
== Logging

Neo4j-OGM uses SLF4J to log statements.
In production, you can set the log level in a file called *logback.xml* to be found at the root of the classpath.
Please see the link:http://logback.qos.ch/manual/[Logback manual] for further details.

