[[reference:connecting]]
= Connecting to the Graph

In order to interact with mapped entities and the Neo4j graph, your application will require a `Session`, which is provided by the `SessionFactory`.

[[reference:connecting:session-factory]]
== SessionFactory

The `SessionFactory` is needed by OGM to create instances of `Session` as required.
This also sets up the object-graph mapping metadata when constructed, which is then used across all `Session` objects that it creates.
The packages to scan for domain object metadata should be provided to the `SessionFactory` constructor.

As seen in the configuration section, this is done by providing the `SessionFactory` a configuration object:
[source, java]
----
SessionFactory sessionFactory = new SessionFactory(configuration, "com.mycompany.app.domainclasses");
----

Or directly a Neo4j Java driver instance:

This can be done by providing to the `SessionFactory` a configuration object:
[source, java]
----
SessionFactory sessionFactory = new SessionFactory(driver, "com.mycompany.app.domainclasses");
----

Multiple packages may be provided as well.
If you would rather just pass in specific classes you can also do that via an overloaded constructor.

.Multiple packages
[source, java]
----
SessionFactory sessionFactory = new SessionFactory(configuration, "first.package.domain", "second.package.domain",...);
----

NOTE: The `SessionFactory` is an expensive object to create because it scans all the requested packages to build up metadata.
 It should typically be set up once during life of your application.
