[[reference:connecting]]
= Connecting to the Graph

In order to interact with mapped entities and the Neo4j graph, your application will require a `Session`, which is provided by the `SessionFactory`.

[[reference:connecting:session-factory]]
== SessionFactory

The `SessionFactory` is needed by Neo4j-OGM to create instances of `Session` as required.
This also sets up the object-graph mapping metadata when constructed, which is then used across all `Session` objects that it creates.
The packages to scan for domain object metadata should be provided to the `SessionFactory` constructor.

NOTE: The `SessionFactory` is an expensive object to create because it scans all the requested packages to build up metadata.
 It should typically be set up once during life of your application.


=== Create SessionFactory with `Configuration` instance

As seen in the configuration section, this is done by providing the `SessionFactory` a configuration object:
[source, java]
----
SessionFactory sessionFactory = new SessionFactory(configuration, "com.mycompany.app.domainclasses");
----

=== Create SessionFactory with `Driver` instance

This can be done by providing to the `SessionFactory` a driver instance:
[source, java]
----
SessionFactory sessionFactory = new SessionFactory(driver, "com.mycompany.app.domainclasses");
----

==== Embedded driver instance

If a pre-configured embedded database is needed, it can be passed into the embedded driver.
It is possible to either use a configuration file
[source, java]
----
GraphDatabaseService db = new GraphDatabaseFactory()
            .newEmbeddedDatabaseBuilder(new File(storeDir))
            .loadPropertiesFromFile(pathToConfigFile)
            .newDatabase();
----

or set the setting parameters programmatically.

[source, java]
----
GraphDatabaseService db = new GraphDatabaseFactory()
            .newEmbeddedDatabaseBuilder(new File(storeDir))
            .setConfig( GraphDatabaseSettings.pagecache_memory, "512M" )
            .newDatabase();
----

and pass them into the `EmbeddedDriver`.

[source, java]
----
EmbeddedDriver driver = new EmbeddedDriver(db)

SessionFactory sessionFactory = new SessionFactory(driver, "com.mycompany.app.domainclasses");
----

=== Multiple entity packages
Multiple packages may be provided as well.
If you would rather just pass in specific classes you can also do that via an overloaded constructor.

.Multiple packages
[source, java]
----
SessionFactory sessionFactory = new SessionFactory(configuration, "first.package.domain", "second.package.domain",...);
----
