[[reference:connecting]]
= Connecting to the Graph

In order to interact with mapped entities and the Neo4j graph, your application will require a `Session`, which is provided by the `SessionFactory`.

[[reference:connecting:session-factory]]
== SessionFactory

The `SessionFactory` is needed by OGM to create instances of `Session` as required.
This also sets up the object-graph mapping metadata when constructed, which is then used across all `Session` objects that it creates.
The packages to scan for domain object metadata should be provided to the `SessionFactory` constructor.
Multiple packages may be provided as well.
If you would rather just pass in specific classes you can also do that via an overloaded constructor.
The `SessionFactory` must also be configured.
There are two ways this can be done.
Please see the section <<reference:configuration, Configuration>> for further details.

.Multiple packages
[source, java]
----
SessionFactory sessionFactory = new SessionFactory("first.package.domain", "second.package.domain",...);
----

Note that the `SessionFactory` should typically be set up once during life of your application.
