[[reference:type-conversion]]
= Type Conversion

The object-graph mapping framework provides support for default and bespoke type conversions, which allow you to configure how certain data types are mapped to nodes or relationships in Neo4j.
If you start with a new Neo4j project on Neo4j 3.4+, you should consider using the <<reference:native-property-types, native type support>> of OGM for all temporal types.

[[reference:type-conversion:built-in]]
== Built-in type conversions

Neo4j-OGM will automatically perform the following type conversions:

* Any object that extends `java.lang.Number` (including `java.math.BigInteger` and `java.math.BigDecimal`) to a String property
* binary data (as `byte[]` or `Byte[]`) to base-64 String as Cypher does not support byte arrays
* `java.lang.Enum` types using the enum's `name()` method and `Enum.valueOf()`
* `java.util.Date` to a String in the ISO 8601 format: "yyyy-MM-dd'T'HH:mm:ss.SSSXXX" (using `DateString.ISO_8601`)
* `java.time.Instant` to a String in the ISO 8601 with timezone format: "yyyy-MM-dd'T'HH:mm:ss.SSSZ" (using `DateTimeFormatter.ISO_INSTANT`)
* `java.time.LocalDate` to a String in the ISO 8601 with format: "yyyy-MM-dd" (using `DateTimeFormatter.ISO_LOCAL_DATE`)
* `java.time.LocalDateTime` to a String in the ISO 8601 with format: "yyyy-MM-dd'T'HH:mm:ss" (using `DateTimeFormatter.ISO_LOCAL_DATE_TIME`)
* `java.time.OffsetDateTime` to a String in the ISO 8601 with format: "YYYY-MM-dd'T'HH:mm:ss+01:00" / "YYYY-MM-dd'T'HH:mm:ss'Z'" (using `DateTimeFormatter.ISO_OFFSET_DATE_TIME`)

`java.time.Instant` based dates are stored in the database using UTC.

Two dedicated annotations are provided to modify the date conversion:

. `@DateString`
. `@DateLong`

They need to be applied to an attribute for a custom string format or in case you want to store a date or datetime value as long:

.Example of user-defined date format
[source, java]
----
public class MyEntity {

    @DateString("yy-MM-dd")
    private Date entityDate;
}
----

Alternatively, if you want to store `java.util.Date` or `java.time.Instant` as long values, use the `@DateLong` annotation:

.Example of date stored as a long value
[source, java]
----
public class MyEntity {

    @DateLong
    private Date entityDate;
}
----

Collections of primitive or convertible values are also automatically mapped by converting them to arrays of their type or strings respectively.

[NOTE]
Arrays are not supported for `java.time.Instant`, `java.time.LocalDate`, `java.time.LocalDateTime`, `java.time.OffsetDateTime`.
Collections are not supported for `java.time.Instant`.

=== Lenient conversion
It is possible to explicitly assign the build-in converter annotations to the corresponding fields.
This provides the advantage of being able to use the `lenient` attribute that will get be read by the converters.
The supported annotations are `@DateString`, `@EnumString` and `@NumberString`.
.Example of lenient converter usage
[source, java]
----
public class MyEntity {

    @DateString(lenient = true)
    private Date entityDate;
}
----

The lenient feature is currently only supported by string-based converters to allow the conversion of blank strings from the database.

[[reference:type-conversion:custom]]
== Custom Type Conversion

In order to define bespoke type conversions for particular members, you can annotate a field with `@Convert`.
One of either two convert implementations can be used.
For simple cases where a single property maps to a single field, with type conversion, specify an implementation of `AttributeConverter`.

.Example of mapping a single property to a field
[source,java]
----
public class MoneyConverter implements AttributeConverter<DecimalCurrencyAmount, Integer> {

   @Override
   public Integer toGraphProperty(DecimalCurrencyAmount value) {
       return value.getFullUnits() * 100 + value.getSubUnits();
   }

   @Override
   public DecimalCurrencyAmount toEntityAttribute(Integer value) {
       return new DecimalCurrencyAmount(value / 100, value % 100);
   }

}
----

You could then apply this to your class as follows:

[source,java]
----
@NodeEntity
public class Invoice {

   @Convert(MoneyConverter.class)
   private DecimalCurrencyAmount value;
   ...
}
----

When more than one node property is to be mapped to a single field, use: `CompositeAttributeConverter`.

[[reference:type-conversion:custom:using-composite-types]]
.Example of mapping multiple node entity properties onto a single instance of a type
[source,java]
----
/**
* This class maps latitude and longitude properties onto a Location type that encapsulates both of these attributes.
*/
public class LocationConverter implements CompositeAttributeConverter<Location> {

    @Override
    public Map<String, ?> toGraphProperties(Location location) {
        Map<String, Double> properties = new HashMap<>();
        if (location != null)  {
            properties.put("latitude", location.getLatitude());
            properties.put("longitude", location.getLongitude());
        }
        return properties;
    }

    @Override
    public Location toEntityAttribute(Map<String, ?> map) {
        Double latitude = (Double) map.get("latitude");
        Double longitude = (Double) map.get("longitude");
        if (latitude != null && longitude != null) {
            return new Location(latitude, longitude);
        }
        return null;
    }

}
----

And just as with an `AttributeConverter`, a `CompositeAttributeConverter` could be applied to your class as follows:

[source,java]
----
@NodeEntity
public class Person {

   @Convert(LocationConverter.class)
   private Location location;
   ...
}
----

