[[reference:events]]
= Events

Neo4j-OGM supports persistence events.
This section describes how to intercept update and delete events.

You may also check the `@PostLoad` annotation which is described <<reference:annotating-entities:postload, here>>.

[[reference:events:types]]
== Event types

There are four types of events:

....
Event.LIFECYCLE.PRE_SAVE
Event.LIFECYCLE.POST_SAVE
Event.LIFECYCLE.PRE_DELETE
Event.LIFECYCLE.POST_DELETE
....

Events are fired for every `@NodeEntity` or `@RelationshipEntity` object that is created, updated or deleted, or otherwise affected by a save or delete request.
This includes:

* The top-level objects or objects being created, modified or deleted.
* Any connected objects that have been modified, created or deleted.
* Any objects affected by the creation, modification or removal of a relationship in the graph.

[NOTE]
====
Events will only fire when one of the `session.save()` or `session.delete()` methods is invoked.
Directly executing Cypher queries against the database using `session.query()` will not trigger any events.
====

[[reference:events:interfaces]]
== Interfaces

The events mechanism introduces two new interfaces, `Event` and `EventListener`.

*The Event interface*

The `Event` interface is implemented by `PersistenceEvent`.
Whenever an application wishes to handle an event it will be given an instance of `Event`, which exposes the following methods:

[source, java]
----
public interface Event {

    Object getObject();
    LIFECYCLE getLifeCycle();

    enum LIFECYCLE {
        PRE_SAVE, POST_SAVE, PRE_DELETE, POST_DELETE
    }
}
----

*The event listener interface*

The `EventListener` interface provides methods allowing implementing classes to handle each of the different `Event` types:

[source, java]
----
public interface EventListener {

    void onPreSave(Event event);
    void onPostSave(Event event);
    void onPreDelete(Event event);
    void onPostDelete(Event event);

}
----

[NOTE]
====
Although the `Event` interface allows you to retrieve the event type, in most cases, your code won't need it because the `EventListener` provides methods to capture each type of event explicitly.
====

[[reference:events:registering]]
== Registering an EventListener

There are two way to register an event listener:

- on an individual `Session`
- across multiple sessions by using a `SessionFactory`

In this example we register an anonymous EventListener to inject a UUID onto new objects before they're saved

[source, java]
----
class AddUuidPreSaveEventListener implements EventListener {

    void onPreSave(Event event) {
        DomainEntity entity = (DomainEntity) event.getObject():
        if (entity.getId() == null) {
            entity.setUUID(UUID.randomUUID());
        }
    }
    void onPostSave(Event event) {
    }
    void onPreDelete(Event event) {
    }
    void onPostDelete(Event event) {
}

EventListener eventListener = new AddUuidPreSaveEventListener();

// register it on an individual session
session.register(eventListener);

// remove it.
session.dispose(eventListener);

// register it across multiple sessions
sessionFactory.register(eventListener);

// remove it.
sessionFactory.deregister(eventListener);

----

[NOTE]
====
It is possible and sometimes desirable to add several EventListener objects to the session, depending on the application’s requirements.
For example, our business logic might require us to add a UUID to a new object, as well as manage wider concerns such as ensuring that a particular persistence event won’t leave our domain model in a logically inconsistent state.
It is usually a good idea to separate these concerns into different objects with specific responsibilities, rather than having one single object try to do everything.
====

[[reference:events:listener-adapter]]
== Using the EventListenerAdapter

The `EventListener` above is fine, but we've had to create three methods for events we don't intend to handle.
It would be preferable if we didn't have to do this each time we needed an `EventListener`.

The `EventListenerAdapter` is an abstract class providing a no-op implementation of the `EventListener` interface.
If you don't need to handle all the different types of persistence event you can create a subclass of `EventListenerAdapter` instead and override just the methods for the event types you're interested in.

For example:

[source, java]
----
class PreSaveEventListener extends EventListenerAdapter {
    @Override
    void onPreSave(Event event) {
        DomainEntity entity = (DomainEntity) event.getObject();
        if (entity.id == null) {
            entity.UUID = UUID.randomUUID();
        }
    }
}
----

[[reference:events:disposing-listener]]
== Disposing of an EventListener

Something to bear in mind is that once an `EventListener` has been registered it will continue to respond to all persistence events.
Sometimes you may want only to handle events for a short period of time, rather than for the duration of the entire session.

If you are done with an `EventListener` you can stop it from firing any more events by invoking `session.dispose(...)`, passing in the `EventListener` to be disposed of.

[NOTE]
====
The process of collecting persistence events prior to dispatching them to any `EventListeners` adds a small performance overhead to the persistence layer.
Consequently, Neo4j-OGM is configured to suppress the event collection phase if there are no `EventListeners` registered with the `Session`.
Using `dispose()` when you're finished with an EventListener is good practice!
====

To remove an event listener across multiple sessions use the `deregister` method on the `SessionFactory`.

[[reference:events:connected-objects]]
== Connected objects

As mentioned previously, events are not only fired for the top-level objects being saved but for all their connected objects as well.

Connected objects are any objects reachable in the domain model from the top-level object being saved.
Connected objects can be many levels deep in the domain model graph.

In this way, the events mechanism allows us to capture events for objects that we didn't explicitly save ourselves.

[source, java]
----
// initialise the graph
Folder folder = new Folder("folder");
Document a = new Document("a");
Document b = new Document("b");
folder.addDocuments(a, b);

session.save(folder);

// change the names of both documents and save one of them
a.setName("A");
b.setName("B");

// because `b` is reachable from `a` (via the common shared folder) they will both be persisted,
// with PRE_SAVE and POST_SAVE events being fired for each of them
session.save(a);
----

[[reference:events:events-and-types]]
== Events and types

When we delete a type, all the nodes with a label corresponding to that type are deleted in the graph.
The affected objects are not enumerated by the events mechanism (they may not even be known).
Instead, `_DELETE` events will be raised for the type:

[source, java]
----
    // 2 events will be fired when the type is deleted.
    // - PRE_DELETE Document.class
    // - POST_DELETE Document.class
    session.delete(Document.class);
----

[[reference:events:events-and-collections]]
== Events and collections

When saving or deleting a collection of objects, separate events are fired for each object in the collection, rather than for the collection itself.

[source, java]
----
Document a = new Document("a");
Document b = new Document("b");

// 4 events will be fired when the collection is saved.
// - PRE_SAVE a
// - PRE_SAVE b
// - POST_SAVE a
// - POST_SAVE b

session.save(Arrays.asList(a, b));
----

[[reference:events:events-ordering]]
== Event ordering

Events are partially ordered.
`PRE_` events are guaranteed to fire before any `POST_` event within the same `save` or `delete` request.
However, the *internal* ordering of the `PRE_` events and `POST_` events with the request is undefined.

.Example: Partial ordering of events
[source, java]
----
Document a = new Document("a");
Document b = new Document("b");

// Although the save order of objects is implied by the request, the PRE_SAVE event for `b`
// may be fired before the PRE_SAVE event for `a`, and similarly for the POST_SAVE events.
// However, all PRE_SAVE events will be fired before any POST_SAVE event.

session.save(Arrays.asList(a, b));
----

[[reference:events:relationship]]
== Relationship events

The previous examples show how events fire when the underlying *node* representing an entity is updated or deleted in the graph.
Events are also fired when a save or delete request results in the modification, addition or deletion of a *relationship* in the graph.

For example, if you delete a `Document` object that is contained in the documents collection of a `Folder`,
events will be fired for the `Document` as well as the `Folder`,
to reflect the fact that the relationship between the folder and the document has been removed in the graph.

.Example: Deleting a `Document` attached to a `Folder`
[source, java]
----
Folder folder = new Folder();
Document a = new Document("a");
folder.addDocuments(a);
session.save(folder);

// When we delete the document, the following events will be fired
// - PRE_DELETE a
// - POST_DELETE a
// - PRE_SAVE folder  <1>
// - POST_SAVE folder
session.delete(a);
----

<1> Note that the `folder` events are `_SAVE` events, not `_DELETE` events.
The `folder` was not deleted.

[WARNING]
====
The event mechanism does not try to synchronise your domain model.
In this example, the folder is still holding a reference to the `Document`, even though it no longer exists in the graph.
As always, your code must take care of domain model synchronisation.
====

[[reference:events:uniqueness]]
== Event uniqueness

The event mechanism guarantees to not fire more than one event of the same type for an object in a save or delete request.

.Example: Multiple changes, single event of each type
[source, java]
----
 // Even though we're making changes to both the folder node, and its relationships,
 // only one PRE_SAVE and one POST_SAVE event will be fired.
 folder.removeDocument(a);
 folder.setName("newFolder");
 session.save(folder);
----
