[[reference:getting-started]]
= Getting Started

[[reference:getting-started:versions]]
== Versions

Consult the version table to determine which version of Neo4j-OGM to use with a particular version of Neo4j and related technologies.

=== Compatibility

[frame="topbot",options="header"]
|======================
|Neo4j-OGM Version   |Neo4j Version^1^
|3.2.x               |3.2.x, 3.3.x, 3.4.x, 3.5.x, 4.0.x^2^, 4.1.x^2^, 4.2.x^2^, 4.3.x^2,5^, 4.4.x^2,5^
|3.1.x               |3.1.x, 3.2.x, 3.3.x, 3.4.x
|3.0.x^3^            |3.1.9, 3.2.12, 3.3.4, 3.4.4
|2.1.x^4^            |2.3.9, 3.0.11, 3.1.6
|2.0.2^4^            |2.3.8, 3.0.7
|2.0.1^4^            |2.2.x, 2.3.x
|======================

^1^ __The latest supported bugfix versions.__ +

^2^ __These versions are only supported over Bolt.__ +

^3^ __These versions are no longer actively developed.__ +

^4^ __These versions are no longer actively developed or supported.__ +

^5^ __Neo4j-OGM 3.2.24+ only.__ +

=== Transitive dependencies

The following table list transitive dependencies between specific versions of projects related to Neo4j-OGM.
When reporting issues or asking for help on StackOverflow or neo4j-users slack channel always
verify versions used (e.g through `mvn dependency:tree`) and report them as well.

[frame="topbot",options="header"]
|======================
|Spring Boot Version    | Spring Data Release Train |Spring Data Neo4j Version | Neo4j-OGM Version
|2.3                    | Neumann                   |5.3                       | 3.2
|2.2                    | Moore                     |5.2                       | 3.2
|2.1                    | Lovelace                  |5.1                       | 3.1
|2.0^1^                 | Kay                       |5.0                       | 3.0
|1.5^2^                 | Ingalls                   |4.2                       | 2.1
|1.4^2^                 | Hopper                    |4.1                       | 2.0
|======================

^1^ __These versions are no longer actively developed.__ +

^2^ __These versions are no longer actively developed or supported.__ +

NOTE: Starting with Spring Boot 2.4, Spring Data Neo4j (version 6+) does not include Neo4j-OGM anymore.

[[reference:getting-started:dependency-management]]
== Dependency Management

For building an application, your build automation tool needs to be configured to include the Neo4j-OGM dependencies.

Neo4j-OGM dependencies consist of `neo4j-ogm-core`, together with the relevant dependency declarations on the driver you want to use.
Neo4j-OGM provides support for connecting to Neo4j by configuring one of the following Drivers:

- `neo4j-ogm-bolt-driver` - Uses native Bolt protocol to communicate between Neo4j-OGM and a remote Neo4j instance.
- `neo4j-ogm-bolt-native-types` - Support for all of Neo4j's property types through the Bolt protocol.
- `neo4j-ogm-http-driver` - Uses HTTP to communicate between Neo4j-OGM and a remote Neo4j instance.
- `neo4j-ogm-embedded-driver` - Creates an in-memory Neo4j instance and uses it.
- `neo4j-ogm-embedded-native-types` - Support for all of Neo4j's property types in an embedded scenario.

Neo4j-OGM projects can be built using Maven, Gradle or any other build system that utilises Maven's artifact repository structure.

[[reference:getting-started:dependency-management:maven]]
=== Maven

In the `<dependencies>` section of your `pom.xml` add the following:

.Maven dependencies
[source, xml, subs="attributes, specialcharacters"]
----
<dependency>
    <groupId>org.neo4j</groupId>
    <artifactId>neo4j-ogm-core</artifactId>
    <version>{ogm-version}</version>
    <scope>compile</scope>
</dependency>

<!-- Only add if you're using the Bolt driver -->
<dependency>
    <groupId>org.neo4j</groupId>
    <artifactId>neo4j-ogm-bolt-driver</artifactId>
    <version>{ogm-version}</version>
    <scope>runtime</scope>
</dependency>

<!-- Only add if you're using the HTTP driver -->
<dependency>
    <groupId>org.neo4j</groupId>
    <artifactId>neo4j-ogm-http-driver</artifactId>
    <version>{ogm-version}</version>
    <scope>runtime</scope>
</dependency>

<!-- Only add if you're using the Embedded driver -->
<dependency>
    <groupId>org.neo4j</groupId>
    <artifactId>neo4j-ogm-embedded-driver</artifactId>
    <version>{ogm-version}</version>
    <scope>runtime</scope>
</dependency>
<dependency>
    <groupId>org.neo4j</groupId>
    <artifactId>neo4j</artifactId>
    <version>{neo4j-version}</version>
    <scope>runtime</scope>
</dependency>
----

Please also have a look at <<reference:native-property-types:supported-drivers, the native type system>> to take advantage of Neo4j-OGM's support for native temporal and spatial types.

[[reference:getting-started:dependency-management:gradle]]
=== Gradle

Ensure the following dependencies are added to you `build.gradle`:

.Gradle dependencies
[source, groovy, subs="attributes"]
----
dependencies {
    compile 'org.neo4j:neo4j-ogm-core:{ogm-version}'
    runtime 'org.neo4j:neo4j-ogm-bolt-driver:{ogm-version}' // Only add if you're using the Bolt driver
    runtime 'org.neo4j:neo4j-ogm-http-driver:{ogm-version}' // Only add if you're using the HTTP driver
    runtime 'org.neo4j:neo4j-ogm-embedded-driver:{ogm-version}' //  Only add if you're using the Embedded driver
    runtime 'org.neo4j:neo4j:{neo4j-version}' //  Only add if you're using the Embedded driver
}
----

