[[reference:indexing]]
= Indexing

Indexing is used in Neo4j to quickly find nodes and relationships from which to start graph operations.

[[reference:indexing:indexes-and-constraints]]
== Indexes and Constraints
Indexes based on labels and properties are supported with the `@Index` annotation.
Any property field annotated with `@Index` will have an appropriate schema index created.
For `@Index(unique=true)` a constraint is created.

You may add as many indexes or constraints as you like to your class.
A class outside any inheritance hierarchy leads to the creation of indexes for its annotated fields on its label.
A class inheriting from a super-class and declaring an index on a field shadowing the same field of the super class leads to the creation of an index for that field on it’s own label.
A non-abstract super-class will index that field on it’s corresponding label as well.
In cases where there is no index definition in a sub-class at al, the first index-defining super class will define the index on its label in the database.

[[reference:indexing:composite]]
== Composite Indexes and Node Key Constraints
Composite indexes based on label and multiple properties are supported with `@CompositeIndex` annotation.
The annotation is to be placed at the class level.
All properties specified must exist within the class or one of its superclasses.
It is possible to create multiple composite indexes by repeating the annotation.

Providing `unique=true` parameter will create a node key constraint instead of a composite index.

[NOTE]
This feature is only supported by Neo4j Enterprise 3.2 and higher.

[[reference:indexing:existence-constraint]]
== Existence constraints
Existence constraints for a property is supported with `@Required` annotation.
It is possible to annotate properties in both node entities and relationship entities.
For node entities the label of declaring class is used to create the constraint.
For relationship entities the relationship type is used - such type must be defined on leaf class.

[NOTE]
This feature is only supported by Neo4j Enterprise 3.1 and higher.

[[reference:indexing:creation]]
== Index Creation

By default index management is set to `None`.

[NOTE]
From our experience with this feature usage we see this as an development time feature.
Usually indexes should get created within the database.
At most in test scenarios there is no guarantee that an index is created before the test runs because of its
asynchronous creation.

If you would like Neo4j-OGM to manage your schema creation there are several ways to go about it.

Only classes marked with `@Index`, `@CompositeIndex` or `@Required` will be used.
Indexes will always be generated with the containing class's label and the annotated property's name.
An abstract class containing indexes or constraints must have `@NodeEntity` annotation present.
Index generation behaviour can be defined in `ogm.properties` by defining a property called: `indexes.auto` and providing a value of:

Below is a table of all options available for configuring Auto-Indexing.

|===
|Option|Description|Properties Example|Java Example

| *none (default)*
| Nothing is done with index and constraint annotations.
| -
| -

| *validate*
| Make sure the connected database has all indexes and constraints in place before starting up
| indexes.auto=validate
| config.setAutoIndex("validate");

| *assert*
| Drops all constraints and indexes on startup then builds indexes based on whatever is represented in Neo4j-OGM by `@Index`.
  Handy during development.
| indexes.auto=assert
| config.setAutoIndex("assert");

| *update*
| Builds indexes based on whatever is represented in Neo4j-OGM by `@Index`.
  Indexes will be changed to constraints and vise versa if the definition in db differs from metadata.
 Handy during development
| indexes.auto=update
| config.setAutoIndex("update");

| *dump*
| Dumps the generated constraints and indexes to a file.
  Good for setting up environments.
  none: Default.
  Simply marks the field as using an index.
| indexes.auto=dump
  indexes.auto.dump.dir=<a directory>
  indexes.auto.dump.filename=<a filename>
| config.setAutoIndex("dump");
  config.setDumpDir("XXX");
  config.setDumpFilename("XXX");

|===
