[[reference:indexing]]
= Indexing

Indexing is used in Neo4j to quickly find nodes and relationships from which to start graph operations.
Indexes are also employed to ensure uniqueness of elements with certain labels and properties.

[NOTE]
====
Please note that the lucene-based manual indexes are deprecated with Neo4j 2.0.
The default index is now based on labels and schema indexes and the related old APIs have been deprecated as well.
The "legacy" index framework should only be used for fulltext and spatial indexes which are not currently supported via schema-based indexes.
====

Previous version of the OGM have restricted developers to only be able to find unique Objects the internal Neo4j ID.
This can be a problem for users when running Neo4j across restarts as this can result in key duplication.
In order to support querying for unique objects via business or synthetic (e.g. UUID) properties, the OGM can now
enforce uniqueness constraints on certain properties to make lookups easier.  On top of this, many users have the
use case of wanting to save their objects via this same property and in effect have the OGM run the `MERGE`
operation using the same property to identify the object.

[[reference:indexing:indexes-and-constraints]]
== Indexes and Constraints
Indexes and unique constraints based on labels and properties are supported as of version `2.1.0` with the `@Index` annotation.
Any property field annotated with `@Index` will use have an appropriate schema index created. For `@Index(unique=true)` a constraint is created.

You may add as many indexes or constraints as you like to your class.  If you annotate a field in a class that is part of an inheritance hierarchy then the index or constraint will only be added to that class's label.

[[reference:indexing:creation]]
== Index Creation

By default index management is set to `None`.

If you would like the OGM to manage your schema creation there are several ways to go about it.

Only classes marked with `@Index` will be used. Indexes will always be generated with the containing class's label and the annotated property's name.
Index generation behaviour can be defined in `ogm.properties` by defining a property called: `indexes.auto` and providing a value of:

Below is a table of all options available for configuring Auto-Indexing.

|===
|Option|Description|Properties Example|Java Example

| *none (default)*
| Nothing is done with index and constraint annotations.
| -
| -

| *validate*
| Make sure the connected database has all indexes and constraints in place before starting up
| indexes.auto=validate
| config.setAutoIndex("validate");

| *assert*
| Drops all constraints and indexes on startup then builds indexes based on whatever is represented in OGM by `@Index`. Handy during development
| indexes.auto=assert
| config.setAutoIndex("assert");

| *dump*
| Dumps the generated constraints and indexes to a file. Good for setting up environments. none: Default. Simply marks the field as using an index.
| indexes.auto=dump
  indexes.auto.dump.dir=<a directory>
  indexes.auto.dump.filename=<a filename>
| config.setAutoIndex("dump");
  config.setDumpDir("XXX");
  config.setDumpFilename("XXX");

|===

[[reference:indexing:primary-constraints]]
== Primary Constraints

The OGM can now be used to look up or merge entities based on a unique constraint. This unique constraint is known as a _primary_ constraint.
It can be enabled through the index annotation like so: `Index(unique=true, primary=true)`.

[NOTE]
Fields marked with `unique=false, primary=true` together will be ignored.

Improvements have also been made to `Session` to allow you to load a particular object via this primary constraint.

`T Session.load(Class<T>, U id)`, where `T` is the highest class in a class hierarchy and
a primary constraint of type `U` is defined on a field in that same class.

[NOTE]
There may only be one `primary=true` index per Class hierarchy.

[[reference:indexing:primary-constraints:merging]]
=== Merging

When an object is created via a call to `Session.save(Object)` a check is made to see if that object's class has a primary
constraint associated with it. If it does that constraint will always as part of a Cypher `MERGE` operation, otherwise a regular
`CREATE` will be used.
