[[reference:indexing]]
= Indexing

Indexing is used in Neo4j to quickly find nodes and relationships from which to start graph operations.

[[reference:indexing:indexes-and-constraints]]
== Indexes and Constraints
Indexes based on labels and properties are supported with the `@Index` annotation.
Any property field annotated with `@Index` will have an appropriate schema index created.
For `@Index(unique=true)` a constraint is created.

You may add as many indexes or constraints as you like to your class.
If you annotate a field in a class that is part of an inheritance hierarchy then the index or constraint will only be added to that class's label.

[[reference:indexing:primary-constraints]]
== Primary Constraints

[WARNING]
The `primary` property of the `@Index` annotation is deprecated since OGM 3 and should not be used.
The primary key is solely provided by the `@Id` annotation.
See <<reference:annotating-entities:entity-identifier, Entity identifier>> for more information.

[[reference:indexing:creation]]
== Index Creation

By default index management is set to `None`.

If you would like the OGM to manage your schema creation there are several ways to go about it.

Only classes marked with `@Index` will be used. Indexes will always be generated with the containing class's label and the annotated property's name.
Index generation behaviour can be defined in `ogm.properties` by defining a property called: `indexes.auto` and providing a value of:

Below is a table of all options available for configuring Auto-Indexing.

|===
|Option|Description|Properties Example|Java Example

| *none (default)*
| Nothing is done with index and constraint annotations.
| -
| -

| *validate*
| Make sure the connected database has all indexes and constraints in place before starting up
| indexes.auto=validate
| config.setAutoIndex("validate");

| *assert*
| Drops all constraints and indexes on startup then builds indexes based on whatever is represented in OGM by `@Index`. Handy during development
| indexes.auto=assert
| config.setAutoIndex("assert");

| *dump*
| Dumps the generated constraints and indexes to a file. Good for setting up environments. none: Default. Simply marks the field as using an index.
| indexes.auto=dump
  indexes.auto.dump.dir=<a directory>
  indexes.auto.dump.filename=<a filename>
| config.setAutoIndex("dump");
  config.setDumpDir("XXX");
  config.setDumpFilename("XXX");

|===
