[[reference:introduction]]
= Introduction

Neo4j OGM is a fast object-graph mapping library for Neo4j, optimised for server-based installations utilising Cypher.

It aims to simplify development with the Neo4j graph database and like JPA, it uses annotations on simple POJO domain objects to do so.

With a focus on performance, the OGM introduces a number of innovations, including:

- non-reflection based classpath scanning for much faster startup times;
- variable-depth persistence to allow you to fine-tune requests according to the characteristics of your graph;
- smart object-mapping to reduce redundant requests to the database, improve latency and minimise wasted CPU cycles; and
- user-definable session lifetimes, helping you to strike a balance between memory-usage and server request efficiency in your applications.

[[reference:introduction:overview]]
== Overview

This reference documentation is broken down into sections to help the user understand specifics of how the OGM works.

.Getting started
To get started with your OGM application, you need only your domain model and the <<reference:annotating-entities, annotations>> provided by the library.
You use annotations to mark domain objects to be reflected by nodes and relationships of the graph database.
For individual fields the annotations allow you to declare how they should be processed and mapped to the graph.
For property fields and references to other entities this is straightforward.


.Configuration
This section covers how to get everything set up for your project.

.Adding Neo4j graph queries
To use advanced functionality like Cypher queries, a basic understanding of the graph data model is required.
The graph data model is explained in the chapter about <<introduction, Neo4j>>.


.Managing relationships
Relationships between entities are first class citizens in a graph database and therefore worth a <<reference:annotating-entities:relationship, section of it's own>> describing their usage in Neo4j OGM.


.Session
Neo4j OGM offers a <<reference:session, session>> for interacting with the mapped entities and the Neo4j graph database.


.Mapping strategies
Because Neo4j is a schema-free database, the OGM uses a simple mechanism to map Java types to Neo4j nodes using labels.
How that works is explained here: <<reference:typerepresentationstrategy, entity type representation>>.


.Transactional support
Neo4j uses transactions to guarantee the integrity of your data and Neo4j OGM supports this fully.
The implications of this are described <<reference:session:transactions, here>>.


.Event handling
The Events mechanism allows users to register event listeners for handling persistence events related both to top-level objects being saved as well as connected objects.
<<reference:events, Event handling>> is discussed in more detail later in the reference chapter.
