[[reference:introduction]]
= Introduction

Neo4j-OGM is a fast object-graph mapping library for Neo4j, optimised for server-based installations utilising Cypher.

It aims to simplify development with the Neo4j graph database and like JPA, it uses annotations on simple POJO domain objects to do so.

With a focus on performance, Neo4j-OGM introduces a number of innovations, including:

- non-reflection based classpath scanning for much faster startup times
- variable-depth persistence to allow you to fine-tune requests according to the characteristics of your graph
- smart object-mapping to reduce redundant requests to the database, improve latency and minimise wasted CPU cycles
- user-definable session lifetimes, helping you to strike a balance between memory-usage and server request efficiency in your applications.

[[reference:introduction:overview]]
== Overview

This reference documentation is broken down into sections to help the user understand specifics of how Neo4j-OGM works.

Getting started::
Getting started can sometimes be a chore.
What versions of Neo4j-OGM do you need?
Where do you get them from?
What build tool should you use?
<<reference:getting-started, Getting Started>> is the perfect place to well... get started!


Configuration::
Drivers, logging, properties, configuration via Java.
How to make sense of all the options?
<<reference:configuration, Configuration>> has got you covered.


Annotating your Domain Objects::
To get started with your Neo4j-OGM application, you need only your domain model and the <<reference:annotating-entities, annotations>> provided by the library.
You use annotations to mark domain objects to be reflected by nodes and relationships of the graph database.
For individual fields the annotations allow you to declare how they should be processed and mapped to the graph.
For property fields and references to other entities this is straightforward.
Because Neo4j is a schema-free database, Neo4j-OGM uses a simple mechanism to map Java types to Neo4j nodes using labels.
Relationships between entities are first class citizens in a graph database and therefore worth a <<reference:annotating-entities:relationship, section of it's own>> describing their usage in Neo4j-OGM.

Connecting to the Database::
Managing how you connect to the database is important.
<<reference:connecting,Connecting to the Database>> has all the details on what needs to happen to get you up and running.


Indexing and Primary Constraints::
Indexing is an important part of any database.
Neo4j-OGM provides a variety of features to support the management of Indexes as well as the ability
to query your domain objects by something other than the internal Neo4j id.
<<reference:indexing, Indexing>> has everything you will want to know when it comes to getting that working.

Interacting with the Graph Model::
Neo4j-OGM offers a <<reference:session, session>> for interacting with the mapped entities and the Neo4j graph database.
Neo4j uses transactions to guarantee the integrity of your data and Neo4j-OGM supports this fully.
The implications of this are described in the transactions section.
To use advanced functionality like Cypher queries, a basic understanding of the graph data model is required.
The graph data model is explained in the chapter about in the introduction chapter.


Type Conversion::
Neo4j-OGM provides support for default and bespoke type conversions, which allow you to configure how certain data types are mapped to nodes or relationships in Neo4j.
See <<reference:type-conversion,Type Conversion>> for more details.


Filtering your domain objects::
Filters provides a simple API to append criteria to your stock `Session.loadX()` behaviour.
This is covered in more detail in <<reference:filters,Filters>>.

Reacting to Persistence events::
The Events mechanism allows users to register event listeners for handling persistence events related both to top-level objects being saved as well as connected objects.
<<reference:events, Event handling>> discusses all the aspects of working with events.

Testing in your application::
Sometimes you want to be able to run your tests against an in-memory version of Neo4j-OGM.
<<reference:testing,Testing>> goes into more detail of how to set that up.

Support for High Availability::
For those using Neo4j Enterprise, support for high availability is extremely important.
The chapter on <<reference:ha,High Availability>> goes into all the options Neo4j-OGM provides to support this.
