[[reference-preface]]
= About the Neo4j OGM library

Neo4j OGM is a fast object-graph mapping library for Neo4j, optimised for server-based installations and utilising Cypher via the transactional HTTP Endpoint.
Focused on performance, it introduces a number of innovations, including non-reflection based classpath scanning for much faster startup times; variable-depth persistence to allow you to fine-tune requests according to the characteristics of your graph; smart object-mapping to reduce redundant requests to the database, improve latency and minimise wasted CPU cycles; and user-definable session lifetimes, helping you to strike a balance between memory-usage and server request efficiency in your applications.

Neo4j OGM aims to simplify development with the Neo4j graph database.
Like JPA, it uses annotations on simple POJO domain objects.
Together with metadata, the annotations drive mapping the POJO entities and their fields to nodes, relationships, and properties in the graph database.


[[reference-compatibility]]
== Compatibility

The following table lists compatibility of the OGM with different versions of Neo4j.

[width="40%",frame="topbot",options="header,footer"]
|======================
|Neo4j-OGM Version |Neo4j Version
|2.1.0+            |2.3.x, 3.0.x, 3.1.x
|2.0.2+            |2.3.x, 3.0.x
|2.0.1             |2.2.x, 2.3.x
|1.1.5             |2.1.x, 2.2.x, 2.3.x
|======================


[[reference-driver-implementations]]
== Multiple driver implementations

As of 2.0, the OGM provides support for connecting to Neo4j using different drivers.
The following drivers are available.

- Http driver
- Embedded driver
- Bolt driver

Please see the <<reference-setup>> for more details about how to configure the OGM to use the driver you require.


[[reference-cypher]]
== Cypher

Cypher is Neo4j's powerful query language.
It is understood by all the different drivers in the OGM which means that your application code should run identically, whichever driver you choose to use.
This makes application development much easier: you can use the Embedded Driver for your integration tests, and then plug in the Http Driver or the Bolt Driver when deploying your code into a production client-server environment.


[[reference-design-considerations]]
== Design considerations

The OGM attempts to minimise the Cypher payload when persisting your objects to the graph.
This is important for two reasons.
Firstly in client-server mode, every network interaction involves an overhead (both bandwidth but more so latency) which impacts the response times of your application.
Secondly, requests containing redundant operations (such as updating an object which hasn't changed) are unnecessary, and have similar impacts.
We have approached this problem in a number of ways:


[[reference-variable-depth-persistence]]
=== Variable-depth persistence

You can now tailor your persistence requests according to the characteristics of the portions of your graph you want to work with.
This means you can choose to make deeper or shallower fetches based on fine tuning the types and amounts of data you want to transfer based on your individual constraints.

If you know that you aren't going to need an object's related objects, you can choose not to fetch them by specifying the fetch-depth as 0.
Alternatively if you know that you will always want to a person's complete set of friends-of-friends, you can set the depth to 2.


[[reference-smart-object-mapping]]
=== Smart object-mapping

Neo4j OGM introduces smart object-mapping.
This means that all other things being equal, it is possible to reliably detect which nodes and relationships needs to be changed in the database, and which don't.

Knowing what needs to be changed means we don't need to flood Neo4j with requests to update objects that don't require changing, or create relationships that already exist.
We can minimise the amount of data we send across the wire as a result, which results in a faster network interaction, and fewer CPU cycles consumed on the server.


[[reference-user-definable-session-lifetime]]
=== User-definable Session lifetime

Supporting the smart object-mapping capability is the `Session` whose lifetime can be managed in code.
For example, associated with single _fetch-update-save_ cycle or unit of work.

The advantage of longer-running sessions is that you will be able to make more efficient requests to the database at the expense of the additional memory associated with the session.
The advantage of shorter sessions is they impose almost no overhead on memory, but will result in less efficient requests to Neo4j when storing and retrieving data.

