[[reference_preface]]
= About the Neo4j OGM Library

Neo4j OGM is a fast object-graph mapping library for Neo4j, optimised for server-based installations and utilising Cypher via the transactional HTTP Endpoint.
Focused on performance, it introduces a number of innovations, including non-reflection based classpath scanning for much faster startup times;
variable-depth persistence to allow you to fine-tune requests according to the characteristics of your graph;
smart object-mapping to reduce redundant requests to the database, improve latency and minimise wasted CPU cycles;
and user-definable session lifetimes, helping you to strike a balance between memory-usage and server request efficiency in your applications.

Neo4j OGM aims to simplify development with the Neo4j graph database.
Like JPA, it uses annotations on simple POJO domain objects.
Together with metadata, the annotations drive mapping the POJO entities and their fields to nodes, relationships, and properties in the graph database.

= Overview

The basic concepts of the Object-Graph Mapping (OGM) library are explained in this chapter.

== Getting Started
To get started with a simple application, you need only your domain model and (optionally) the annotations (see <<reference_programming-model_annotations>>) provided by the library.
You use annotations to mark domain objects to be reflected by nodes and relationships of the graph database.
For individual fields the annotations allow you to declare how they should be processed and mapped to the graph.
For property fields and references to other entities this is straightforward.

== Adding Neo4j Graph Queries
To use advanced functionality like Cypher queries, a basic understanding of the graph data model is required.
The graph data model is explained in the chapter about Neo4j, see <<neo4j>>.

== Managing Relationships
Relationships between entities are first class citizens in a graph database and therefore worth a separate chapter
(<<reference_programming-model_relationships>>) describing their usage in Neo4j OGM.

== Session
Neo4j OGM offers a <<reference_programming-model_session,Session>> for interacting with the mapped entities and the Neo4j graph database.

== Mapping Strategies
Because Neo4j is a schema-free database, the OGM uses a simple mechanism to map Java types to Neo4j nodes using labels.
How that works is explained here: <<reference_programming-model_typerepresentationstrategy,Entity Type Representation>>.

== Transactional Support
Neo4j uses transactions to guarantee the integrity of your data and Neo4j OGM supports this fully.
The implications of this are described in <<reference_programming-model_transactions>>.

////
== Examples
The provided samples, which are also publicly hosted on http://github.com/neo4j-examples[Github], are explained in <<reference_samples>>.
////

== Performance
Neo4j OGM has been built with performance in mind.
More information can be found in <<reference_performance,Performance Considerations>>.
