[[reference_preface]]
= About the Neo4j OGM Library

Neo4j OGM is a fast object-graph mapping library for Neo4j, optimised for server-based installations and utilising Cypher via the transactional HTTP Endpoint.
Focused on performance, it introduces a number of innovations, including non-reflection based classpath scanning for much faster startup times;
variable-depth persistence to allow you to fine-tune requests according to the characteristics of your graph;
smart object-mapping to reduce redundant requests to the database, improve latency and minimise wasted CPU cycles;
and user-definable session lifetimes, helping you to strike a balance between memory-usage and server request efficiency in your applications.

Neo4j OGM aims to simplify development with the Neo4j graph database.
Like JPA, it uses annotations on simple POJO domain objects.
Together with metadata, the annotations drive mapping the POJO entities and their fields to nodes, relationships, and properties in the graph database.

== Design Considerations
The design of the OGM is based on the understanding that the majority of users wants to run application servers that connect to remote database instances.
They will therefore need to communicate "over the wire".
Neo4j provides the capability to do this now with its powerful Cypher language, which is exposed via a remote protocol.

What we have attempted to do is to ensure that, as much as possible, we don't overload that communication channel.
This is important for two reasons.
Firstly, every network interaction involves an overhead (both bandwidth but more so latency) which impacts the response times of your application.
Secondly, network requests containing redundant operations (such as updating an object which hasn't changed) are unnecessary, and have similar impacts.
We have approached this problem in a number of ways:

=== Variable-depth persistence
You can now tailor your persistence requests according to the characteristics of the portions of your graph you want to work with.
This means you can choose to make deeper or shallower fetches based on fine tuning the types and amounts of data you want to transfer based on your individual constraints.

If you know that you aren't going to need an object's related objects, you can choose not to fetch them by specifying the fetch-depth as 0.
Alternatively if you know that you will always want to a person's complete set of friends-of-friends, you can set the depth to 2.

=== Smart object-mapping
Neo4j OGM introduces smart object-mapping.
This means that all other things being equal, it is possible to reliably detect which nodes and relationships needs to be changed in the database, and which don't.

Knowing what needs to be changed means we don't need to flood Neo4j with requests to update objects that don't require changing, or create relationships that already exist.
We can minimise the amount of data we send across the wire as a result, which results in a faster network interaction, and fewer CPU cycles consumed on the server.

=== User-definable Session lifetime
Supporting the smart object-mapping capability is the `Session` whose lifetime can be managed in code. For example, associated with single _fetch-update-save_ cycle or unit of work.

The advantage of longer-running sessions is that you will be able to make more efficient requests to the database at the expense of the additional memory associated with the session.
The advantage of shorter sessions is they impose almost no overhead on memory, but will result in less efficient requests to Neo4j when storing and retrieving data.


= Overview

The basic concepts of the Object-Graph Mapping (OGM) library are explained in this chapter.

== Getting Started
To get started with a simple application, you need only your domain model and (optionally) the annotations (see <<reference_programming-model_annotations>>) provided by the library.
You use annotations to mark domain objects to be reflected by nodes and relationships of the graph database.
For individual fields the annotations allow you to declare how they should be processed and mapped to the graph.
For property fields and references to other entities this is straightforward.

== Adding Neo4j Graph Queries
To use advanced functionality like Cypher queries, a basic understanding of the graph data model is required.
The graph data model is explained in the chapter about Neo4j, see <<neo4j>>.

== Managing Relationships
Relationships between entities are first class citizens in a graph database and therefore worth a separate chapter
(<<reference_programming-model_relationships>>) describing their usage in Neo4j OGM.

== Session
Neo4j OGM offers a <<reference_programming-model_session,Session>> for interacting with the mapped entities and the Neo4j graph database.

== Mapping Strategies
Because Neo4j is a schema-free database, the OGM uses a simple mechanism to map Java types to Neo4j nodes using labels.
How that works is explained here: <<reference_programming-model_typerepresentationstrategy,Entity Type Representation>>.

== Transactional Support
Neo4j uses transactions to guarantee the integrity of your data and Neo4j OGM supports this fully.
The implications of this are described in <<reference_programming-model_transactions>>.

////
== Examples
The provided samples, which are also publicly hosted on http://github.com/neo4j-examples[Github], are explained in <<reference_samples>>.
////


