[[reference:session]]
= Using Neo4j-OGM Session

The `Session` provides the core functionality to persist objects to the graph and load them in a variety of ways.

[[reference:session:configuration]]
== Session Configuration

A `Session` is used to drive the object-graph mapping framework.
It keeps track of the changes that have been made to entities and their relationships.
The reason it does this is so that only entities and relationships that have changed get persisted on save, which is particularly efficient when working with large graphs.
Once an entity is tracked by the session, reloading this entity within the scope of the same session will result in the session cache returning the previously loaded entity.
However, the subgraph in the session will expand if the entity or its related entities retrieve additional relationships from the graph.

The lifetime of the `Session` can be managed in code.
For example, associated with single _fetch-update-save_ cycle or unit of work.

If your application relies on long-running sessions then you may not see changes made from other users and find yourself working with outdated objects.
On the other hand, if your sessions have a too narrow scope then your save operations can be unnecessarily expensive, as updates will be made to all objects if the session isn't aware of the those that were originally loaded.

There's therefore a trade off between the two approaches.
In general, the scope of a `Session` should correspond to a "unit of work" in your application.

If you want to fetch fresh data from the graph, then this can be achieved by using a new session or clearing the current sessions context using `Session.clear()`.
This feature should be used with caution because it will clear the whole cache and it needs to get rebuild on the next operation.
Also Neo4j-OGM won't be able to do any dirty tracking between the operations that are separated by the `Session.clear()` call.

[[reference:session:basic-operations]]
== Basic operations

Basic operations are limited to CRUD operations on entities and executing arbitrary Cypher queries; more low-level manipulation of the graph database is not possible.

Given that the Neo4j-OGM framework is driven by Cypher queries alone, there's no way to work directly with `Node` and `Relationship` objects in remote server mode.

If you find yourself in trouble because of the omission of these features, then your best option is to
write a Cypher query to perform the operations on the nodes/relationships instead.

In general, for low-level, very high-performance operations like complex graph traversals you will get the best performance by writing a server-side extension.
For most purposes, though, Cypher will be performant and expressive enough to perform the operations that you need.

[[reference:session:persisting-entities]]
== Persisting entities

`Session` allows to `save`, `load`, `loadAll` and `delete` entities with transaction handling and exception translation managed for you.
The eagerness with which objects are retrieved is controlled by specifying the _depth_ argument to any of the load methods.

Entity persistence is performed through the `save()` method on the underlying `Session` object.

Under the bonnet, the implementation of `Session` has access to the `MappingContext` that keeps track of the data that has been loaded from Neo4j during the lifetime of the session.
Upon invocation of `save()` with an entity, it checks the given object graph for changes compared with the data that was loaded from the database.
The differences are used to construct a Cypher query that persists the deltas to Neo4j before repopulating it's state based on the response from the database server.

Neo4j-OGM doesn't automatically commit when a transaction closes, so an explicit call to `save(...)` is required in order to persist changes to the database.


.Persisting entities
====
[source, java]
----
@NodeEntity
public class Person {
   private String name;
   public Person(String name) {
      this.name = name;
   }
}

// Store Michael in the database.
Person p = new Person("Michael");
session.save(p);
----
====


[[reference:session:persisting-entities:save-depth]]
=== Save depth

As mentioned previously, `save(entity)` is overloaded as `save(entity, depth)`, where depth dictates the number of related entities to save starting from the given entity.
The default depth, -1, will persist properties of the specified entity as well as every modified entity in the object graph reachable from it.
This means that *all affected* objects in the entity model that are reachable from the root object being persisted will be modified in the graph.
This is the recommended approach because it means you can persist all your changes in one request.
Neo4j-OGM is able to detect which objects and relationships require changing, so you won't flood Neo4j with a bunch of objects that don't require modification.
You can change the persistence depth to any value, but you should not make it less than the value used to load the corresponding data or you run the risk of not having changes you expect to be made actually being persisted in the graph.
A depth of 0 will persist only the properties of the specified entity to the database.
Please be aware that a depth of 0 for a relationship operation will always also affect the linked nodes.

Specifying the save depth is handy when it comes to dealing with complex collections, that could potentially be very expensive to load.

.Relationship save cascading
====
[source, java]
----
@NodeEntity
class Movie {
    String title;
    Actor topActor;
    public void setTopActor(Actor actor) {
        topActor = actor;
    }
}

@NodeEntity
class Actor {
    String name;
}

Movie movie = new Movie("Polar Express");
Actor actor = new Actor("Tom Hanks");

movie.setTopActor(actor);
----
====

Neither the actor nor the movie has been assigned a node in the graph.
If we were to call `session.save(movie)`, then Neo4j-OGM would first create a node for the movie.
It would then note that there is a relationship to an actor, so it would save the actor in a cascading fashion.
Once the actor has been persisted, it will create the relationship from the movie to the actor.
All of this will be done atomically in one transaction.

The important thing to note here is that if `session.save(actor)` is called instead, then only the actor will be persisted.
The reason for this is that the actor entity knows nothing about the movie entity - it is the movie entity that has the reference to the actor.
Also note that this behaviour is not dependent on any configured relationship direction on the annotations.
It is a matter of Java references and is not related to the data model in the database.

In the following example, the actor and the movie are both managed entities, having both been previously persisted to the graph:

.Cascade for modified fields
====
[source,java]
----
actor.setBirthyear(1956);
session.save(movie);
----
====

[NOTE]
====
In this case, even though the movie has a reference to the actor, the property change on the actor *will be* persisted by the call to `save(movie)`.
The reason for this is, as mentioned above, that cascading will be done for fields that have been modified and reachable from the root object being saved.
====


In the example below, `session.save(user,1)` will persist all modified objects reachable from `user` up to one level deep.
This includes `posts` and `groups` but not entities related to them, namely `author`, `comments`, `members` or `location`.
A persistence depth of 0 i.e. `session.save(user,0)` will save only the properties on the user, ignoring any related entities.
In this case, `fullName` is persisted but not friends, posts or groups.


.Persistence Depth
[source, java]
----
public class User  {

   private Long id;
   private String fullName;
   private List<Post> posts;
   private List<Group> groups;

}

public class Post {

   private Long id;
   private String name;
   private String content;
   private User author;
   private List<Comment> comments;

}

public class Group {

   private Long id;
   private String name;
   private List<User> members;
   private Location location;

}
----

[[reference:session:loading-entities]]
== Loading Entities

Entities can be loaded from Neo4j-OGM through the use of the `session.loadXXX()` methods or via `session.query()`/`session.queryForObject()` which will
accept your own Cypher queries (See section below on <<reference:session:loading-entities:cypher-queries, cypher queries>>).

Neo4j-OGM includes the concept of persistence horizon (depth).
On any individual request, the persistence horizon indicates how many relationships should be traversed in the graph when loading or saving data.
A horizon of zero means that only the root object's properties will be loaded or saved, a horizon of 1 will include the root object and all its immediate neighbours, and so on.
This attribute is enabled via a `depth` argument available on all session methods, but Neo4j-OGM chooses sensible defaults so that you don't have to specify the depth attribute unless you want change the default values.

[[reference:session:loading-entities:load-depth]]
=== Load depth

By default, loading an instance will map that object's simple properties and its immediately-related objects (i.e. depth = 1).
This helps to avoid accidentally loading the entire graph into memory, but allows a single request to fetch not only the object of immediate interest, but also its closest neighbours, which are likely also to be of interest.
This strategy attempts to strike a balance between loading too much of the graph into memory and having to make repeated requests for data.

If parts of your graph structure are deep and not broad (for example a linked-list), you can increase the load horizon for those nodes accordingly.
Finally, if your graph will fit into memory, and you'd like to load it all in one go, you can set the depth to -1.

On the other hand when fetching structures which are potentially very "bushy" (e.g. lists of things that themselves have many relationships), you may want to set the load horizon to 0 (depth = 0) to avoid loading thousands of objects most of which you won't actually inspect.

[NOTE]
====
When loading entities with a custom depth less than the one used previously to load the entity within the session, existing relationships will not be flushed from the session; only new entities and relationships are added.
This means that reloading entities will always result in retaining related objects loaded at the highest depth within the session for those entities.
If it is required to load entities with a lower depth than previously requested, this must be done on a new session, or after clearing your current session with `Session.clear()`.
====

[[reference:session:loading-entities:query-strategy]]
=== Query Strategy
WhenNeo4j-OGM loads entities through `load*` methods (including ones with filters) it uses `LoadStrategy` to generate the `RETURN` part of the query.

Available load strategies are

* *schema load strategy* - uses metadata on domain entities and pattern comprehensions to retrieve nodes and relationships (default since Neo4j-OGM 3.0)

* *path load strategy* - uses paths from root node to fetch related nodes, `p=(n)-[0..]-()` (default before Neo4j-OGM 3.0)

The strategy can be overridden globally by calling `SessionFactory.setLoadStrategy(strategy)` or for single session only
(e.g. when different strategy is more effective for given query) by calling `Session.setLoadStrategy(strategy)`


[[reference:session:loading-entities:cypher-queries]]
=== Cypher queries

Cypher is Neo4j's powerful query language.
It is understood by all the different drivers in Neo4j-OGM which means that your application code should run identically, whichever driver you choose to use.
This makes application development much easier: you can use the Embedded Driver for your integration tests, and then plug in the HTTP Driver or the Bolt Driver when deploying your code into a production client-server environment.


The `Session` also allows execution of arbitrary Cypher queries via its `query` and `queryForObject` methods.
Cypher queries that return tabular results should be passed into the `query` method which returns an `Result`.
This consists of `QueryStatistics` representing statistics of modifying cypher statements if applicable, and an `Iterable<Map<String,Object>>` containing the raw data, which can be either used as-is or converted into a richer type if needed.
The keys in each `Map` correspond to the names listed in the return clause of the executed Cypher query.

`queryForObject` specifically queries for entities and as such, queries supplied to this method must return nodes and not individual properties.

Query methods that retrieve mapped objects may be used in cases where the query generated by load strategy does not have
sufficient performance.

Such queries should return nodes and optionally relationships.
For a relationship to be mapped both start and end node must be returned.

Query methods returning particular domain type collect the result from all result columns and nested structures in these
(e.g. collected lists, maps etc..) and return as single `Iterable<T>`.
Use `Result Session.query(java.lang.String, java.util.Map<java.lang.String,?>)` to retrieve only objects in particular column.

[NOTE]
====
In the current version, custom queries do not support paging, sorting or a custom depth.
In addition, it does not support mapping a path to domain entities, as such, a path should not be returned from a Cypher query.
Instead, return nodes and relationships to have them mapped to domain entities.

Modifications made to the graph via Cypher queries directly will not be reflected in your domain objects within the session.
====


[[reference:session:loading-entities:sorting-and-paging]]
=== Sorting and paging

Neo4j-OGM supports Sorting and Paging of results when using the Session object.
The Session object methods take independent arguments for Sorting and Pagination

.Paging
[source, java]
----
Iterable<World> worlds = session.loadAll(World.class,
                                        new Pagination(pageNumber,itemsPerPage), depth)
----

.Sorting
[source, java]
----
Iterable<World> worlds = session.loadAll(World.class,
                                        new SortOrder().add("name"), depth)
----

.Sort in descending order
[source, java]
----
Iterable<World> worlds = session.loadAll(World.class,
                                        new SortOrder().add(SortOrder.Direction.DESC,"name"))
----

.Sorting with paging
[source, java]
----
Iterable<World> worlds = session.loadAll(World.class,
                                        new SortOrder().add("name"), new Pagination(pageNumber,itemsPerPage))
----

[NOTE]
====
Neo4j-OGM does not yet support sorting and paging on custom queries.
====

