[[reference_setup]]
= Getting started

Neo4j OGM dramatically simplifies development, but some setup is required.
For building the application, Maven needs to be configured to include the Neo4j OGM dependencies and after the build setup is complete, the application needs to be configured to make use of Neo4j OGM.

Neo4j OGM projects can be built using Maven, Gradle or Ant/Ivy.

== Dependencies for Neo4j OGM

.Maven dependencies for Neo4j OGM
[source,xml]
----
<dependency>
    <groupId>org.neo4j</groupId>
    <artifactId>neo4j-ogm</artifactId>
    <version>{version}</version>
</dependency>
----

== Session Configuration

In order to interact with mapped entities and the Neo4j graph, your application will require a `Session`,
 which is provided by the `SessionFactory`.

.Creating a SessionFactory
[source,java]
----

SessionFactory sessionFactory = new SessionFactory("org.neo4j.example.domain");
Session session = sessionFactory.openSession("http://localhost:7474");

----

=== SessionFactory Bean

The `SessionFactory` is needed by OGM to create instances of `org.neo4j.ogm.session.Session` as required.
This also sets up the object-graph mapping metadata when constructed, which is then used across all `Session` objects that it creates.
As seen in the above example, the packages to scan for domain object metadata should be provided to the `SessionFactory` constructor.

Note that the `SessionFactory` should typically be set up once during life of your application.

=== Session Bean

A `Session` is used to drive the object-graph mapping framework. It keeps track of the changes that have been made to entities and their relationships.
The reason it does this is so that only entities and relationships that have changed get persisted on save, which is particularly efficient when working with large graphs.
Note, however, that the `Session` *doesn't ever return cached objects* so there's no risk of getting stale data on load; it always hits the database.

The lifetime of the `Session` can be managed in code. For example, associated with single _fetch-update-save_ cycle or unit of work.

If your application relies on long-running sessions and doesn't reload entities then you may not see changes made from other users and find yourself working with outdated objects.
On the other hand, if your sessions have too narrow a scope then your save operations can be unnecessarily expensive, as updates will be made to all objects if the session isn't aware of the those that were originally loaded.

There's therefore a trade off between the two approaches.
In general, the scope of a `Session` should correspond to a "unit of work" in your application.

If you make sure you load fresh data at the beginning of each unit of work then data integrity shouldn't be a problem.

The `Session` requires a URL with which to access the remote Neo4j database. For test environments, `Neo4jIntegrationTestRule.url()` can be used instead. See the section on <<reference_programming-model_testing,Testing>>.
