[[reference:getting-started]]
= Getting Started

[[reference:getting-started:versions]]
== Versions

Consult the version table to determine which version of the OGM to use with a particular version of Neo4j and related technologies.

[width="80%",frame="topbot",options="header,footer"]
|======================
|Neo4j-OGM Version   |Neo4j Version       | Compatible with Spring Data Neo4j Version
|2.1.0+              |2.3.x, 3.0.x, 3.1.x | 4.2.x
|2.0.2+              |2.3.x, 3.0.x        | 4.1.2 - 4.1.6+
|2.0.1^*^            |2.2.x, 2.3.x        | 4.1.0 - 4.1.1
|1.1.5^*^            |2.1.x, 2.2.x, 2.3.x | 4.0.x
|======================

^*^ __These versions are no longer actively developed or supported.__

[[reference:getting-started:dependency-management]]
== Dependency Management

For building an application, your build automation tool needs to be configured to include the Neo4j OGM dependencies.


The OGM dependencies consist of `neo4j-ogm-core`, together with the relevant dependency declarations on the driver you want to use.  OGM 2.1  provides support for connecting to Neo4j by configuring one of the following Drivers:

- `neo4j-ogm-http-driver` - Uses HTTP to communicate between the OGM and a remote Neo4j instance.
- `neo4j-ogm-embedded-driver` - Connects directly to the Neo4j database engine.
- `neo4j-ogm-bolt-driver` - Uses native Bolt protocol to communicate between the OGM and a remote Neo4j instance.

If you're not using a particular driver, you don't need to declare it.

Neo4j OGM projects can be built using Maven, Gradle or any other build system that utilises Maven's artifact repository structure.

[[reference:getting-started:dependency-management:maven]]
=== Maven

In the `<dependencies>` section of your `pom.xml` add the following:

.Maven dependencies
[source, xml, subs="attributes, specialcharacters"]
----
<dependency>
    <groupId>org.neo4j</groupId>
    <artifactId>neo4j-ogm-core</artifactId>
    <version>{version}</version>
    <scope>compile</scope>
</dependency>

<!-- Only add if you're using the HTTP driver -->
<dependency>
    <groupId>org.neo4j</groupId>
    <artifactId>neo4j-ogm-http-driver</artifactId>
    <version>{version}</version>
    <scope>runtime</scope>
</dependency>

<!-- Only add if you're using the Embedded driver -->
<dependency>
    <groupId>org.neo4j</groupId>
    <artifactId>neo4j-ogm-embedded-driver</artifactId>
    <version>{version}</version>
    <scope>runtime</scope>
</dependency>

<!-- Only add if you're using the Bolt driver -->
<dependency>
    <groupId>org.neo4j</groupId>
    <artifactId>neo4j-ogm-bolt-driver</artifactId>
    <version>{version}</version>
    <scope>runtime</scope>
</dependency>
----

If you plan on using a development (i.e. `SNAPSHOT`) version of the OGM you will need to add the following to the
`<repositories>` section of your `pom.xml`:

.Neo4j Snapshot Repository
[source, xml, subs="attributes, specialcharacters"]
----
<repository>
    <id>neo4j-snapshot-repository</id>
    <name>Neo4j Maven 2 snapshot repository</name>
    <url>http://m2.neo4j.org/content/repositories/snapshots</url>
</repository>
----

[[reference:getting-started:dependency-management:gradle]]
=== Gradle

Ensure the following dependencies are added to you `build.gradle`:

.Gradle dependencies
[source, groovy, subs="attributes"]
----
dependencies {
    compile 'org.neo4j:neo4j-ogm-core:{version}'
    runtime 'org.neo4j:neo4j-ogm-http-driver:{version}' // Only add if you're using the HTTP driver
    runtime 'org.neo4j:neo4j-ogm-embedded-driver:{version}' //  Only add if you're using the Embedded driver
    runtime 'org.neo4j:neo4j-ogm-bolt-driver:{version}' // Only add if you're using the Bolt driver
}
----

If you plan on using a development (i.e. `SNAPSHOT`) version of the OGM you will need to add the following section of your `build.gradle`:

.Neo4j Snapshot Repository
[source, groovy, subs="attributes"]
----
repositories {
    maven { url "http://m2.neo4j.org/content/repositories/snapshots" }
}
----
