[[reference_setup]]
= Getting started

Neo4j OGM dramatically simplifies development, but some setup is required.
For building the application, your build automation tool needs to be configured to include the Neo4j OGM dependencies and after the build setup is complete,
the application needs to be configured to make use of Neo4j OGM.

Neo4j OGM projects can be built using Maven, Gradle or Ant/Ivy.

== Dependencies for Neo4j OGM

.Maven dependencies for Neo4j OGM
[source,xml]
----
<dependency>
    <groupId>org.neo4j</groupId>
    <artifactId>neo4j-ogm</artifactId>
    <version>{version}</version>
</dependency>
----

.Gradle dependencies for Neo4j OGM
[source,xml]
----
dependencies {
    compile 'org.neo4j:neo4j-ogm:{version}'
}
----

.Ivy dependencies for Neo4j OGM
[source,xml]
----
<dependency org="org.neo4j" name="neo4j-ogm" rev="{version}"/>
----

== Setup

In order to interact with mapped entities and the Neo4j graph, your application will require a `Session`,
 which is provided by the `SessionFactory`.

.Creating a SessionFactory
[source,java]
----

SessionFactory sessionFactory = new SessionFactory("org.neo4j.example.domain");
Session session = sessionFactory.openSession("http://localhost:7474");

----

=== SessionFactory

The `SessionFactory` is needed by OGM to create instances of `org.neo4j.ogm.session.Session` as required.
This also sets up the object-graph mapping metadata when constructed, which is then used across all `Session` objects that it creates.
As seen in the example above, the packages to scan for domain object metadata should be provided to the `SessionFactory` constructor.
Multiple packages may be provided as well.

.Multiple packages
[source,java]
----
SessionFactory sessionFactory = new SessionFactory("first.package.domain", "second.package.domain",...);
----

Note that the `SessionFactory` should typically be set up once during life of your application.

=== Session

A `Session` is used to drive the object-graph mapping framework. It keeps track of the changes that have been made to entities and their relationships.
The reason it does this is so that only entities and relationships that have changed get persisted on save, which is particularly efficient when working with large graphs.
Note, however, that the `Session` *doesn't ever return cached objects* so there's no risk of getting stale data on load; it always hits the database.

The lifetime of the `Session` can be managed in code. For example, associated with single _fetch-update-save_ cycle or unit of work.

If your application relies on long-running sessions and doesn't reload entities then you may not see changes made from other users and find yourself working with outdated objects.
On the other hand, if your sessions have too narrow a scope then your save operations can be unnecessarily expensive, as updates will be made to all objects if the session isn't aware of the those that were originally loaded.

There's therefore a trade off between the two approaches.
In general, the scope of a `Session` should correspond to a "unit of work" in your application.

If you make sure you load fresh data at the beginning of each unit of work then data integrity shouldn't be a problem.

== OGM 2.x Configuration

There are two basic ways to configure the OGM, via a properties file, or programmatically.

=== Properties file configuration
By default, the OGM will look for a properties file called "ogm.properties" at startup. If this file exists on the
classpath, it will be used to configure the OGM.

If you want to automatically configure the OGM using a different properties file, you can do so by setting
a System property or Environment variable called 'ogm.properties' that points to the file you want to use. The file
must be available on the classpath.

.Configuring the driver using a properties file

.Http Driver example (userInfo credentials)
```
driver=org.neo4j.ogm.drivers.http.driver.HttpDriver
URI=http://bilbo:baggins@localhost:7474
```

.Http Driver example (separate credentials)
```
driver=org.neo4j.ogm.drivers.http.driver.HttpDriver
URI=http://localhost:7474
username:bilbo
password:baggins
```

.Embedded Driver example (permanent data store)
```
driver=org.neo4j.ogm.drivers.embedded.driver.EmbeddedDriver
URI=file:///tmp/neo4j.db
```

.Embedded Driver example (impermanent data store)
```
driver=org.neo4j.ogm.drivers.embedded.driver.EmbeddedDriver
```

(To use an Impermenant graph database store, omit the URI attribute)


.Bolt Driver example (userInfo credentials)

```
driver=org.neo4j.ogm.drivers.bolt.driver.BoltDriver
URI=bolt://bilbo:baggins@localhost
```

.Bolt Driver example (separate credentials)

```
driver=org.neo4j.ogm.drivers.bolt.driver.BoltDriver
URI=bolt://localhost
username:bilbo
password:baggins
```

.Configuring the cypher compiler using a properties file

You can optionally specify which cypher compiler the OGM should use when generating cypher queries. As of 2.0 only one compiler
implementation is available, but in the future you can expect to be able to choose a compiler that is explicitly tuned to
the version of Neo4j you wish to use. 

_Note: if you don't specify a compiler option, the OGM will select one by default._

.Compiler configuration example (default)
```
compiler=org.neo4j.ogm.compiler.MultiStatementCypherCompiler
```

=== Programmatic configuration

say something here

=== Upgrading from OGM 1.x to 2.x

upgrade steps

== OGM 1.x Configuration

.Driver configuration

_Note: OGM 1.x only supports Http (server-based) connectivity to Neo4j. If you want to use an Embedded database or use
the Bolt protocol to connect with a Neo4j server, you'll need to upgrade to OGM 2.0_

If you're running against Neo4j 2.2 or later and authentication is enabled, you will need to supply connection credentials.
This can be accomplished by supplying the username and password as parameters to the `SessionFactory.openSession` method,
or by embedded them into the URL such as `http://username:password@localhost:7474`.

.Passing connection credentials when opening the session
[source,java]
----
SessionFactory sessionFactory = new SessionFactory("org.neo4j.example.domain");
Session session = sessionFactory.openSession("http://localhost:7474", username, password);
----

.Embedding connection credentials in the URL
[source,java]
----
SessionFactory sessionFactory = new SessionFactory("org.neo4j.example.domain");
Session session = sessionFactory.openSession("http://username:password@localhost:7474");
----

If you don't want to or can't supply credentials as described above, the OGM can use the System properties 
`username` and `password` and supply them with each request to the Neo4j database.

.Setting System properties
[source,java]
----
System.setProperty("username", user);
System.setProperty("password", pass);

SessionFactory sessionFactory = new SessionFactory("org.neo4j.example.domain");
Session session = sessionFactory.openSession("http://localhost:7474");
----

.Compiler configuration
There is no explicit compiler configuration required for OGM 1.x