[[reference:transactions]]
= Transactions

Neo4j is a transactional database, only allowing operations to be performed within transaction boundaries.

Transactions can be managed explicitly by calling the `beginTransaction()` method on the `Session` followed by a `commit()` or `rollback()` as required.

.Transaction management
[source, java]
----

try (Transaction tx = session.beginTransaction()) {
    Person person = session.load(Person.class,personId);
    Concert concert= session.load(Concert.class,concertId);
    Hotel hotel = session.load(Hotel.class,hotelId);
    buyConcertTicket(person,concert);
    bookHotel(person, hotel);
    tx.commit();
} catch (SoldOutException e) {
    tx.rollback();
}
----

NOTE: make sure to always close the transaction by wrapping it in a `try-with-resources` block or by calling `close()` in a `finally` block.

In the example above, the transaction is committed only when both, a concert ticket and hotel room, are available, otherwise, neither booking is made.

*If you do not manage a transaction in this manner, auto commit transactions are provided implicitly* for `Session` methods such as `save`, `load`, `delete`, `execute` and so on.

Transactions are by default `READ_WRITE` but can also be opened as `READ_ONLY`.

.Opening a read only transaction
[source, java]
----
Transaction tx = session.beginTransaction(Transaction.Type.READ_ONLY);
...
----

This is important for clustering where the type of transaction is used to route requests to servers.
See <<reference:ha, the high availability section>>.
