[[reference_programming-model_conversion]]
= Conversion

The object-graph mapping framework provides support for default and bespoke type
conversions, which allow you to configure how certain data types are mapped to nodes or relationships in Neo4j.

[[reference_programming-model_conversion-built_in]]
== Built-In Type Conversions

Neo4j OGM will automatically perform the following type conversions:

- `java.util.Date` to a String in the ISO 8601 format: "yyyy-MM-dd'T'HH:mm:ss.SSSXXX"
- `java.math.BigInteger` to a String property
- `java.math.BigDecimal` to a String property
- binary data (as byte[] or Byte[]) to base-64 String as Cypher does not support byte arrays
- `java.lang.Enum` types using the enum's `name()` method and `Enum.valueOf()`

Two Date converters are provided "out of the box"

. @DateString
. @DateLong

By default, the OGM will use the @DateString propertyConverter as described above. However if you want to use a different date
format, you can annotate your entity attribute accordingly:

.Example of user-defined date format
[source,java]
----
public class MyEntity {

    @DateString("yy-MM-dd")
    private Date entityDate;
}
----

Alternatively, if you want to store Dates as long values, use the @DateLong annotation:

.Example of date stored as a long value
[source,java]
----
public class MyEntity {

    @DateLong
    private Date entityDate;
}
----

Collections of primitive or convertible values are also automatically mapped by converting them to arrays of their type
or strings respectively.

[[reference_programming-model_conversion-custom]]
== Custom Type Conversion

In order to define bespoke type conversions for particular members, you can annotate a field or method with `@Convert`
to specify an implementation of `org.neo4j.ogm.typeconversion.AttributeConverter` to use.

.Example of custom type propertyConverter
[source,java]
----
public class MoneyConverter implements AttributeConverter<DecimalCurrencyAmount, Integer> {

   @Override
   public Integer toGraphProperty(DecimalCurrencyAmount value) {
       return value.getFullUnits() * 100 + value.getSubUnits();
   }

   @Override
   public DecimalCurrencyAmount toEntityAttribute(Integer value) {
       return new DecimalCurrencyAmount(value / 100, value % 100);
   }
    
}
----

You could then apply this to your class as follows:

[source,java]
----
@NodeEntity
public class Invoice {

   @Convert(MoneyConverter.class)
   private DecimalCurrencyAmount value;
   ...
}
----
