[[reference_programming-model_session]]
= Session

The `Session` provides the core functionality to persist objects to the graph and load them in a variety of ways.

== Basic operations

Basic operations are limited to CRUD operations on entities and executing arbitrary Cypher queries; more low-level manipulation of the graph database is not possible.

[NOTE] 
There is no way to manipulate relationship- and node-objects directly.

Given that the Neo4j OGM framework is driven by Cypher queries alone, there's no way to work directly with `Node` and `Relationship` objects in remote server mode.
Similarly, `traverse()` is not supported, again because the underlying query-driven model doesn't handle it in an efficient way.

If you find yourself in trouble because of the omission of these features, then your best options are:

. Write a Cypher query to perform the operations on the nodes/relationships instead
. Write a Neo4j server extension and call it over REST from your application

Of course, there are pros and cons to both of these approaches, but these are largely outside the scope of this document.  
In general, for low-level, very high-performance operations like complex graph traversals you'll get the best performance by writing a server-side extension.  
For most purposes, though, Cypher will be performant and expressive enough to perform the operations that you need.

== Entity-Persistence

`Session` allows to `save`, `load`, `loadAll` and `delete` entities with transaction handling and exception translation managed for you.
The eagerness with which objects are retrieved is controlled by specifying the 'depth' argument to any of the load methods.

== Cypher Queries

The `Session` also allows execution of arbitrary Cypher queries via its `query`, `queryForObject` and `queryForObjects` methods.
Cypher queries that return tabular results should be passed into the `query` method. 
An `Iterable<Map<String,Object>>` containing the raw data is returned, which can be either used as-is or converted into a richer type if needed. 
The keys in each `Map` correspond to the names listed in the return clause of the executed Cypher query.

For the query methods that retrieve mapped objects, the recommended query format is to return a path, which should ensure that known types get mapped correctly and joined together with relationships as appropriate.

For Cypher update operations, `Session` provides an `execute` method, to which an arbitrary Cypher update statement (such as CREATE, MERGE or DELETE) can be passed.

== Transactions

The `Session` provides implicit transactions for some of its methods.
For instance `save` uses them. 
TODO write some more

