[[tutorial-session]]
= Interacting with the model

So our domain entities are annotated, now we're ready persist them to the graph!

== Sessions

The smart object mapping capability is provided by the `Session` object.
A `Session` is obtained from a `SessionFactory`.

We're going to set up the `SessionFactory` xref:tutorial.adoc#tutorial:configuration:sessionfactory[just once] and have it produce as many sessions as required.

The `Session` keeps track of changes made to entities and relationships and persists ones that have been modified on save.
Once an entity is tracked by the session, reloading this entity within the scope of the same session will result in the session cache returning the previously loaded entity.
However, the subgraph in the session will expand if the entity or its related entities retrieve additional relationships from the graph.

For the purpose of this example application, we'll use short living sessions - a new session per operation - to avoid stale data issues.

Our example application will use the following operations:

[source, java]
----
public class MovieService {

    Movie findMovieByTitle(String title) {
        // implementation
    }

    List<Movie> allMovies() {
        // implementation
    }

    Movie updateTagline(String title, String newTagline) {
        // implementation
    }
}
----

These CRUD interactions with the graph are all handled by the `Session`.
Whenever we want to run a unit of work, we open the session and do all operations with the same `Session` instance.
Let's have a look at the implementations (and the constructor with the `SessionFactory` instantiation) of the service:

[source, java]
----
public class MovieService {

    final SessionFactory sessionFactory;

    public MovieService() {
        Configuration config = new Configuration.Builder()
            .uri("neo4j://localhost:7687")
            .credentials("neo4j", "verysecret")
            .build();
        this.sessionFactory = new SessionFactory(config, "org.neo4j.ogm.example");
    }

    Movie findMovieByTitle(String title) {
        Session session = sessionFactory.openSession();
        return Optional.ofNullable(
                session.queryForObject(Movie.class, "MATCH (m:Movie {title:$title}) return m", Map.of("title", title)))
            .orElseThrow(() -> new MovieNotFoundException(title));
    }

    public List<Movie> allMovies() {
        Session session = sessionFactory.openSession();
        return new ArrayList<>(session.loadAll(Movie.class));
    }

    Movie updateTagline(String title, String newTagline) {
        Session session = sessionFactory.openSession();
        Movie movie = session.queryForObject(Movie.class, "MATCH (m:Movie{title:$title}) return m", Map.of("title", title));
        Movie updatedMovie = movie.withTagline(newTagline);
        session.save(updatedMovie);
        return updatedMovie;
    }
}
----

As you can see in the _updateTagline_ method, the `Session` gets opened right at the start to have the loading
and persisting operation within the same instance.

When the service fetches all `Movies`, the default load depth of _1_ gets applied to the operation.
A higher value does not have any impact on our example because we are just loading `Movies` and their direct neighbours.
The chapter on xref:reference.adoc#reference:session:loading-entities:load-depth[load depth] gives you more insights of the default behaviour
of relationship traversal.

== Custom queries and mapping

As you have already seen, we have used custom queries with `Session#query` to fetch a `Movie` by title.
Sometimes you end up with data returning from your query that does not fit into one of the entities, you have defined previously.

Let's say, we want to collect the average rating of a `Movie` joined with all reviewers.
Sure we could do this also in the application itself but preparing data on the database side has not only the benefit of
reducing the data over the wire, but also it's something the database can do much faster in most of the cases.

[source, java]
----
public record MovieRating(String title, float rating, List<String> reviewers) {
}
----

Adding another method to our service including the custom query results in:

[source, java]
----
List<MovieRating> getRatings() {
    Session session = sessionFactory.openSession();
    List<MovieRating> ratings = session.queryDto(
        "MATCH (m:Movie)<-[r:REVIEWED]-(p:Person) RETURN m.title as title, avg(r.rating) as rating, collect(p.name) as reviewers",
        Map.of(),
        MovieRating.class);
    return ratings;
}
----
