name: release

on:
  create:
    tags:
      - '*'

jobs:
  release:
    if: (github.event_name == 'create' && github.event.ref_type == 'tag')
    runs-on: ubuntu-latest
    steps:
      - name: 'Set up JDK'
        uses: actions/setup-java@c1e323688fd81a25caa38c78aa6df2d33d3e20d9 # v4.8.0
        with:
          distribution: zulu
          java-version: 21

      - name: 'Prepare git'
        run: git config --global core.autocrlf false

      - name: 'Prepare branch name'
        if: (github.event_name == 'create' && github.event.ref_type == 'tag')
        run: >
          echo "refName=${GITHUB_REF##*/}" >> $GITHUB_ENV

      - name: 'Checkout relevant branch'
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
        with:
          ref: ${{ env.refName }}
          fetch-depth: 0

      - name: 'Create release'
        env:
          JRELEASER_GITHUB_TOKEN: ${{ secrets.JRELEASER_TOKEN }}
          JRELEASER_SLACK_WEBHOOK: ${{ secrets.JRELEASER_SLACK_WEBHOOK }}
        run: ./mvnw --no-transfer-progress -Djreleaser -DreleaseVersion=${refName:1} jreleaser:announce -pl org.neo4j:neo4j-ogm
